/**
 * SCRAP CROWN v3 — combat-robot part catalog + preset bots.
 * Pure data only. Budget is POINTS (cost); mass is physics only.
 * Every part carries `type` (builder filter) and `faces` (mount surfaces).
 * Look: welded plate, titanium, UHMW, scorched steel — no toy brick palette.
 */
import type {
  BotSpec,
  Catalog,
  PartDef
} from "../sim/types";

/* ------------------------------------------------------------------ */
/* metal / paint palette (0xRRGGBB)                                     */
/* gun 0x2f3336 | raw steel 0x8d9299 | brass 0xb08d57 | rust 0x7a2f20  */
/* paint red 0xc8102e | paint blue 0x1b4a8f | hazard 0xe0a80d          */
/* scorched 0x3a3f45                                                    */
/* ------------------------------------------------------------------ */

const ALL_FACES = ["deck", "underside", "left", "right", "front", "rear"] as const;
const WHEEL_FACES = ["underside", "left", "right"] as const;
const TRACK_FACES = ["left", "right"] as const;
const SPINNER_FACES = ["deck", "front"] as const;
const SAW_DRILL_FACES = ["deck", "front", "left", "right"] as const;
const IMPULSE_FACES = ["deck", "front"] as const;
const STATIC_FACES = ["front", "left", "right", "rear"] as const;
const SKIRT_FACES = ["left", "right", "front", "rear"] as const;
const UTIL_FACES = ["deck", "underside"] as const;
const CHASSIS_FACES = ["deck"] as const;
const INTERNAL_FACES = ["internal"] as const;

export const PARTS: readonly PartDef[] = [
  /* ======================== chassis / frame (5) ======================== */
  {
    id: "chassis-light",
    type: "frame",
    faces: CHASSIS_FACES,
    name: "Light Chassis",
    nameJa: "軽量シャーシ",
    category: "chassis",
    cost: 110,
    mass: 20,
    hp: 280,
    armor: 4,
    cells: [5, 7],
    deck: [5, 7],
    height: 0.1,
    heightCells: 3,
    groundClearance: 0.04,
    invertible: false,
    material: "aluminium",
    color: 0x2f3336,
    blurb: "機動重視の薄肉アルミデッキ。積載は控えめ。",
    internalGrid: [3, 5],
    stockPowerKw: 3.5,
    stockAlternatorKw: 0.6,
    stockChargeKj: 6,
    stockFuelL: 3,
    stockCoolingKw: 2.0
  },
  {
    id: "chassis-medium",
    type: "frame",
    faces: CHASSIS_FACES,
    name: "Medium Chassis",
    nameJa: "中量シャーシ",
    category: "chassis",
    cost: 160,
    mass: 32,
    hp: 380,
    armor: 8,
    cells: [7, 9],
    deck: [7, 9],
    height: 0.12,
    heightCells: 3,
    groundClearance: 0.05,
    invertible: false,
    material: "steel",
    color: 0x8d9299,
    blurb: "溶接鋼板の標準デッキ。多くの構成に対応。",
    internalGrid: [5, 7],
    stockPowerKw: 5.0,
    stockAlternatorKw: 0.9,
    stockChargeKj: 10,
    stockFuelL: 5,
    stockCoolingKw: 3.0
  },
  {
    id: "chassis-heavy",
    type: "frame",
    faces: CHASSIS_FACES,
    name: "Heavy Chassis",
    nameJa: "重量シャーシ",
    category: "chassis",
    cost: 230,
    mass: 48,
    hp: 520,
    armor: 14,
    cells: [9, 11],
    deck: [9, 11],
    height: 0.14,
    heightCells: 4,
    groundClearance: 0.05,
    invertible: false,
    material: "hardox",
    color: 0x3a3f45,
    blurb: "Hardox厚板の大甲板。重いが壊れにくい。",
    internalGrid: [7, 9],
    stockPowerKw: 6.5,
    stockAlternatorKw: 1.2,
    stockChargeKj: 14,
    stockFuelL: 7,
    stockCoolingKw: 4.0
  },
  {
    id: "chassis-invert",
    type: "frame",
    faces: CHASSIS_FACES,
    name: "Invertible Medium",
    nameJa: "インバーテッド中量シャーシ",
    category: "chassis",
    cost: 195,
    mass: 34,
    hp: 380,
    armor: 10,
    cells: [7, 9],
    deck: [7, 9],
    height: 0.12,
    heightCells: 3,
    groundClearance: 0.045,
    invertible: true,
    material: "steel",
    color: 0x2f3336,
    blurb: "上下対称デッキ。逆さでも走れる本格可逆設計。",
    internalGrid: [5, 7],
    stockPowerKw: 5.0,
    stockAlternatorKw: 0.9,
    stockChargeKj: 10,
    stockFuelL: 5,
    stockCoolingKw: 3.0
  },
  {
    id: "chassis-ultralow",
    type: "frame",
    faces: CHASSIS_FACES,
    name: "Ultra-Low Frame",
    nameJa: "超低車高フレーム",
    category: "chassis",
    cost: 145,
    mass: 26,
    hp: 320,
    armor: 7,
    cells: [6, 8],
    deck: [6, 8],
    height: 0.08,
    heightCells: 2,
    groundClearance: 0.025,
    invertible: false,
    material: "aluminium",
    color: 0x2f3336,
    blurb: "底面駆動向けの超低車高フレーム。側面は低い。",
    internalGrid: [4, 4],
    stockPowerKw: 4.0,
    stockAlternatorKw: 0.7,
    stockChargeKj: 8,
    stockFuelL: 4,
    stockCoolingKw: 2.5
  },

  /* ======================== drive: wheel (8) ======================== */
  {
    id: "wheel-small",
    type: "wheel",
    faces: WHEEL_FACES,
    name: "Small Wheel",
    nameJa: "小ホイール",
    category: "drive",
    kind: "wheel",
    cost: 40,
    mass: 4,
    hp: 50,
    armor: 2,
    cells: [1, 1],
    height: 0.1,
    radius: 0.08,
    torque: 22,
    maxOmega: 55,
    friction: 1.0,
    material: "rubber",
    color: 0x3a3f45,
    blurb: "軽量高速。トルクは控えめ。"
  },
  {
    id: "wheel-mid",
    type: "wheel",
    faces: WHEEL_FACES,
    name: "Mid Wheel",
    nameJa: "中ホイール",
    category: "drive",
    kind: "wheel",
    cost: 45,
    mass: 8,
    hp: 70,
    armor: 4,
    cells: [2, 2],
    height: 0.14,
    radius: 0.12,
    torque: 40,
    maxOmega: 48,
    friction: 1.1,
    material: "rubber",
    color: 0x3a3f45,
    blurb: "標準サイズ。トルクと速度のバランス型。"
  },
  {
    id: "wheel-large",
    type: "wheel",
    faces: WHEEL_FACES,
    name: "Large Wheel",
    nameJa: "大ホイール",
    category: "drive",
    kind: "wheel",
    cost: 50,
    mass: 12,
    hp: 85,
    armor: 6,
    cells: [2, 3],
    height: 0.18,
    radius: 0.16,
    torque: 62,
    maxOmega: 35,
    friction: 1.2,
    material: "rubber",
    color: 0x3a3f45,
    blurb: "高トルクの大径輪。段差と押し合いに強い。"
  },
  {
    id: "wheel-grip",
    type: "wheel",
    faces: WHEEL_FACES,
    name: "High-Grip Wheel",
    nameJa: "高グリップホイール",
    category: "drive",
    kind: "wheel",
    cost: 48,
    mass: 7,
    hp: 65,
    armor: 3,
    cells: [2, 2],
    height: 0.13,
    radius: 0.11,
    torque: 36,
    maxOmega: 45,
    friction: 1.45,
    material: "rubber",
    color: 0x1b4a8f,
    blurb: "高μコンパウンド。押し合いと旋回に強い。"
  },
  {
    id: "hub-invert",
    type: "wheel",
    faces: WHEEL_FACES,
    name: "Invertible Hub",
    nameJa: "インバーテッド対応ハブ",
    category: "drive",
    kind: "wheel",
    cost: 95,
    mass: 15,
    hp: 110,
    armor: 8,
    cells: [2, 2],
    height: 0.12,
    radius: 0.11,
    torque: 60,
    maxOmega: 18,
    friction: 1.55,
    material: "steel",
    color: 0x8d9299,
    blurb: "上下両用ハブ。可逆シャーシと組んで逆走を維持。"
  },
  {
    id: "wheel-buggy",
    type: "wheel",
    faces: WHEEL_FACES,
    name: "Fat Buggy Tire",
    nameJa: "極太バギータイヤ",
    category: "drive",
    kind: "wheel",
    cost: 58,
    mass: 14,
    hp: 95,
    armor: 5,
    cells: [2, 3],
    height: 0.2,
    radius: 0.17,
    torque: 55,
    maxOmega: 32,
    friction: 1.35,
    material: "rubber",
    color: 0x3a3f45,
    blurb: "極太オフ路タイヤ。段差と横Gに強いが嵩張る。"
  },
  {
    id: "wheel-spoke",
    type: "wheel",
    faces: WHEEL_FACES,
    name: "Light Spoke Wheel",
    nameJa: "軽量スポークホイール",
    category: "drive",
    kind: "wheel",
    cost: 42,
    mass: 3,
    hp: 40,
    armor: 1,
    cells: [1, 1],
    height: 0.1,
    radius: 0.09,
    torque: 20,
    maxOmega: 62,
    friction: 0.95,
    material: "aluminium",
    color: 0x8d9299,
    blurb: "スポーク軽量輪。最高速向け、耐久は低い。"
  },
  {
    id: "wheel-metal",
    type: "wheel",
    faces: WHEEL_FACES,
    name: "Metal Wheel",
    nameJa: "金属製ホイール",
    category: "drive",
    kind: "wheel",
    cost: 55,
    mass: 11,
    hp: 120,
    armor: 12,
    cells: [2, 2],
    height: 0.13,
    radius: 0.11,
    torque: 38,
    maxOmega: 40,
    friction: 0.9,
    material: "steel",
    color: 0x8d9299,
    blurb: "鋼製ソリッド。グリップは落ちるが武器の直撃に耐える。"
  },

  /* ======================== drive: track (4) ======================== */
  {
    id: "track-std",
    type: "track",
    faces: TRACK_FACES,
    name: "Track Drive",
    nameJa: "標準履帯",
    category: "drive",
    kind: "track",
    cost: 90,
    mass: 16,
    hp: 115,
    armor: 10,
    cells: [2, 4],
    height: 0.12,
    radius: 0.1,
    torque: 58,
    maxOmega: 16,
    friction: 1.6,
    material: "steel",
    color: 0x2f3336,
    blurb: "低速高牽引。最高速は落ちるが押しが強い。"
  },
  {
    id: "track-wide",
    type: "track",
    faces: TRACK_FACES,
    name: "Wide Track",
    nameJa: "幅広履帯",
    category: "drive",
    kind: "track",
    cost: 110,
    mass: 22,
    hp: 140,
    armor: 12,
    cells: [3, 4],
    height: 0.13,
    radius: 0.11,
    torque: 72,
    maxOmega: 14,
    friction: 1.75,
    material: "steel",
    color: 0x2f3336,
    blurb: "接地圧を下げた幅広履帯。押し合いと安定性に優れる。"
  },
  {
    id: "track-rubber",
    type: "track",
    faces: TRACK_FACES,
    name: "Rubber Crawler",
    nameJa: "ゴムクローラ",
    category: "drive",
    kind: "track",
    cost: 85,
    mass: 12,
    hp: 90,
    armor: 6,
    cells: [2, 4],
    height: 0.11,
    radius: 0.09,
    torque: 48,
    maxOmega: 20,
    friction: 1.5,
    material: "rubber",
    color: 0x3a3f45,
    blurb: "軽量ゴムクローラ。静粛で機敏、装甲は薄い。"
  },
  {
    id: "track-stub",
    type: "track",
    faces: TRACK_FACES,
    name: "Stub Track",
    nameJa: "短尺スタブ履帯",
    category: "drive",
    kind: "track",
    cost: 65,
    mass: 9,
    hp: 80,
    armor: 8,
    cells: [2, 2],
    height: 0.1,
    radius: 0.08,
    torque: 40,
    maxOmega: 22,
    friction: 1.4,
    material: "steel",
    color: 0x2f3336,
    blurb: "短いスタブ履帯。低車高の側面に収まりやすい。"
  },

  /* ======================== weapon: spinner / drum (6) ======================== */
  {
    id: "disc-light",
    type: "spinner",
    faces: SPINNER_FACES,
    mechanism: "revolute",
    spinAxis: "horizontal",
    name: "Light Horizontal Disc",
    nameJa: "軽量水平ディスク",
    category: "weapon",
    action: "passive",
    effect: "spin",
    slot: "primary",
    cost: 290,
    mass: 24,
    hp: 160,
    armor: 4,
    cells: [4, 2],
    height: 0.08,
    material: "steel",
    color: 0xc8102e,
    blurb: "軽めの水平スピナー。立ち上がりが速い。",
    damageMul: 2.4,
    selfDamageMul: 0.25,
    reach: 0.18,
    maxOmega: 240,
    spinUpTorque: 40,
    inertia: 0.55
  },
  {
    id: "disc-heavy",
    type: "spinner",
    faces: SPINNER_FACES,
    mechanism: "revolute",
    spinAxis: "horizontal",
    name: "Heavy Horizontal Disc",
    nameJa: "重量水平ディスク",
    category: "weapon",
    action: "passive",
    effect: "spin",
    slot: "primary",
    cost: 380,
    mass: 30,
    hp: 200,
    armor: 6,
    cells: [5, 2],
    height: 0.1,
    material: "hardox",
    color: 0xc8102e,
    blurb: "一撃の重い水平スピナー。自傷にも注意。",
    damageMul: 2.8,
    selfDamageMul: 0.25,
    reach: 0.22,
    maxOmega: 200,
    spinUpTorque: 55,
    inertia: 0.95
  },
  {
    id: "drum-std",
    type: "drum",
    faces: SPINNER_FACES,
    mechanism: "revolute",
    spinAxis: "vertical",
    name: "Vertical Drum",
    nameJa: "垂直ドラム",
    category: "weapon",
    action: "passive",
    effect: "spin",
    slot: "primary",
    cost: 340,
    mass: 32,
    hp: 240,
    armor: 8,
    cells: [4, 3],
    height: 0.16,
    material: "steel",
    color: 0x7a2f20,
    blurb: "縦回転ドラム。安定した継続火力とすくい上げ。",
    damageMul: 2.1,
    selfDamageMul: 0.22,
    reach: 0.14,
    maxOmega: 145,
    spinUpTorque: 70,
    inertia: 1.6
  },
  {
    id: "shell-spinner",
    type: "spinner",
    faces: SPINNER_FACES,
    mechanism: "revolute",
    spinAxis: "vertical",
    name: "Shell Spinner",
    nameJa: "シェルスピナー",
    category: "weapon",
    action: "held",
    effect: "spin",
    slot: "primary",
    cost: 360,
    mass: 34,
    hp: 250,
    armor: 10,
    cells: [5, 3],
    height: 0.18,
    material: "hardox",
    color: 0x3a3f45,
    blurb: "殻ごと回す重量スピナー。押している間だけ加速。",
    damageMul: 2.0,
    selfDamageMul: 0.25,
    reach: 0.16,
    maxOmega: 140,
    spinUpTorque: 65,
    inertia: 1.8
  },
  {
    id: "vert-spinner",
    type: "spinner",
    faces: SPINNER_FACES,
    mechanism: "revolute",
    spinAxis: "vertical",
    name: "Vertical Spinner",
    nameJa: "バーティカルスピナー",
    category: "weapon",
    action: "passive",
    effect: "spin",
    slot: "primary",
    cost: 330,
    mass: 28,
    hp: 190,
    armor: 5,
    cells: [3, 3],
    height: 0.2,
    material: "steel",
    color: 0xc8102e,
    blurb: "縦回転のディスクスピナー。上面と前面に効く。",
    damageMul: 2.5,
    selfDamageMul: 0.24,
    reach: 0.2,
    maxOmega: 210,
    spinUpTorque: 50,
    inertia: 0.8
  },
  {
    id: "eggbeater",
    type: "spinner",
    faces: SPINNER_FACES,
    mechanism: "revolute",
    spinAxis: "horizontal",
    name: "Eggbeater",
    nameJa: "エッグビーター",
    category: "weapon",
    action: "passive",
    effect: "spin",
    slot: "primary",
    cost: 310,
    mass: 26,
    hp: 175,
    armor: 4,
    cells: [3, 3],
    height: 0.16,
    material: "steel",
    color: 0x7a2f20,
    blurb: "二軸の撹拌スピナー。巻き込みと継続ヒット向き。",
    damageMul: 2.2,
    selfDamageMul: 0.22,
    reach: 0.15,
    maxOmega: 180,
    spinUpTorque: 48,
    inertia: 0.7
  },

  /* ======================== weapon: saw (5) ======================== */
  {
    id: "side-saws",
    type: "saw",
    faces: SAW_DRILL_FACES,
    mechanism: "revolute",
    spinAxis: "horizontal",
    pairMount: true,
    name: "Side Saws",
    nameJa: "サイドソー",
    category: "weapon",
    action: "passive",
    effect: "grind",
    slot: "tertiary",
    cost: 180,
    mass: 13,
    hp: 110,
    armor: 3,
    cells: [2, 2],
    height: 0.08,
    material: "steel",
    color: 0x8d9299,
    blurb: "左右に常時回転する切断ソー。寄られても削る。",
    damageMul: 1.15,
    selfDamageMul: 0.15,
    reach: 0.12,
    maxOmega: 290,
    spinUpTorque: 25,
    inertia: 0.22,
    dps: 28
  },
  {
    id: "cutting-disc",
    type: "saw",
    faces: SAW_DRILL_FACES,
    mechanism: "revolute",
    spinAxis: "horizontal",
    name: "Cutting Disc",
    nameJa: "カッティングディスク",
    category: "weapon",
    action: "held",
    effect: "grind",
    slot: "secondary",
    cost: 200,
    mass: 12,
    hp: 100,
    armor: 2,
    cells: [2, 2],
    height: 0.08,
    material: "steel",
    color: 0xe0a80d,
    blurb: "押している間だけ高回転切断。燃料不要。",
    damageMul: 1.2,
    selfDamageMul: 0.1,
    reach: 0.1,
    maxOmega: 300,
    spinUpTorque: 30,
    inertia: 0.18,
    dps: 38,
    fuel: 0
  },
  {
    id: "angle-grinder",
    type: "saw",
    faces: SAW_DRILL_FACES,
    mechanism: "revolute",
    spinAxis: "vertical",
    name: "Angle Grinder",
    nameJa: "アングルグラインダ",
    category: "weapon",
    action: "held",
    effect: "grind",
    slot: "secondary",
    cost: 130,
    mass: 10,
    hp: 90,
    armor: 2,
    cells: [2, 2],
    height: 0.07,
    material: "steel",
    color: 0x8d9299,
    blurb: "安価な補助グラインダ。押している間だけ削る。",
    damageMul: 1.0,
    selfDamageMul: 0.12,
    reach: 0.08,
    maxOmega: 280,
    spinUpTorque: 20,
    inertia: 0.12,
    dps: 22,
    fuel: 0
  },
  {
    id: "chainsaw",
    type: "saw",
    faces: SAW_DRILL_FACES,
    mechanism: "revolute",
    spinAxis: "horizontal",
    name: "Chainsaw",
    nameJa: "チェーンソー",
    category: "weapon",
    action: "held",
    effect: "grind",
    slot: "secondary",
    cost: 220,
    mass: 15,
    hp: 120,
    armor: 3,
    cells: [3, 2],
    height: 0.1,
    material: "steel",
    color: 0xe0a80d,
    blurb: "バー式チェーンソー。接触中に深く食い込む。",
    damageMul: 1.35,
    selfDamageMul: 0.14,
    reach: 0.22,
    maxOmega: 160,
    spinUpTorque: 28,
    inertia: 0.3,
    dps: 42,
    fuel: 0
  },
  {
    id: "disc-saw-large",
    type: "saw",
    faces: SAW_DRILL_FACES,
    mechanism: "revolute",
    spinAxis: "horizontal",
    name: "Large Circular Saw",
    nameJa: "円盤ノコ（大）",
    category: "weapon",
    action: "passive",
    effect: "grind",
    slot: "secondary",
    cost: 250,
    mass: 18,
    hp: 140,
    armor: 4,
    cells: [3, 3],
    height: 0.12,
    material: "hardox",
    color: 0x8d9299,
    blurb: "大径の円盤ノコ。常時回転で装甲を削る。",
    damageMul: 1.4,
    selfDamageMul: 0.16,
    reach: 0.18,
    maxOmega: 220,
    spinUpTorque: 35,
    inertia: 0.45,
    dps: 36
  },

  /* ======================== weapon: drill (3) ======================== */
  {
    id: "drill-auger",
    type: "drill",
    faces: SAW_DRILL_FACES,
    mechanism: "revolute",
    spinAxis: "horizontal",
    name: "Auger Drill",
    nameJa: "オーガードリル",
    category: "weapon",
    action: "held",
    effect: "grind",
    slot: "primary",
    cost: 240,
    mass: 16,
    hp: 130,
    armor: 4,
    cells: [2, 3],
    height: 0.12,
    material: "steel",
    color: 0x8d9299,
    blurb: "螺旋オーガー。単発の貫通は重いが継続DPSは低い。",
    damageMul: 2.6,
    selfDamageMul: 0.12,
    reach: 0.28,
    maxOmega: 90,
    spinUpTorque: 45,
    inertia: 0.5,
    dps: 14,
    fuel: 0
  },
  {
    id: "drill-twin",
    type: "drill",
    faces: SAW_DRILL_FACES,
    mechanism: "revolute",
    spinAxis: "horizontal",
    pairMount: true,
    name: "Twin Drill",
    nameJa: "ツインドリル",
    category: "weapon",
    action: "held",
    effect: "grind",
    slot: "primary",
    cost: 280,
    mass: 20,
    hp: 150,
    armor: 5,
    cells: [3, 2],
    height: 0.11,
    material: "steel",
    color: 0x2f3336,
    blurb: "双頭ドリル。一点集中の貫通を左右で狙う。",
    damageMul: 2.8,
    selfDamageMul: 0.14,
    reach: 0.24,
    maxOmega: 100,
    spinUpTorque: 50,
    inertia: 0.55,
    dps: 16,
    fuel: 0
  },
  {
    id: "drill-pile",
    type: "drill",
    faces: SAW_DRILL_FACES,
    mechanism: "prismatic",
    launch: "punch",
    name: "Pile Bunker",
    nameJa: "パイルバンカー",
    category: "weapon",
    action: "triggered",
    effect: "impulse",
    slot: "primary",
    cost: 300,
    mass: 22,
    hp: 170,
    armor: 6,
    cells: [3, 2],
    height: 0.12,
    material: "hardox",
    color: 0x3a3f45,
    blurb: "杭打ち式バンカー。クールダウン付きの重貫通一撃。",
    damageMul: 2.4,
    selfDamageMul: 0.1,
    reach: 0.4,
    impulse: 1100,
    cooldown: 2.8,
    sweep: 0.35,
    strokeSec: 0.1
  },

  /* ======================== weapon: impulse / clamp (6) ======================== */
  {
    id: "flipper-std",
    type: "flipper",
    faces: IMPULSE_FACES,
    mechanism: "revolute",
    launch: "flip",
    name: "Pneumatic Flipper",
    nameJa: "空圧フリッパー",
    category: "weapon",
    action: "triggered",
    effect: "impulse",
    slot: "primary",
    cost: 320,
    mass: 25,
    hp: 210,
    armor: 6,
    cells: [4, 3],
    height: 0.1,
    material: "steel",
    color: 0xe0a80d,
    blurb: "空圧で相手を宙に舞わせる。ピット送りの本命。",
    damageMul: 0.75,
    selfDamageMul: 0.05,
    reach: 0.2,
    impulse: 1200,
    cooldown: 2.5,
    sweep: 1.2,
    strokeSec: 0.18
  },
  {
    id: "lifter-std",
    type: "lifter",
    faces: IMPULSE_FACES,
    mechanism: "revolute",
    launch: "flip",
    name: "Electric Lifter",
    nameJa: "電動リフター",
    category: "weapon",
    action: "triggered",
    effect: "impulse",
    slot: "primary",
    cost: 230,
    mass: 20,
    hp: 200,
    armor: 6,
    cells: [4, 3],
    height: 0.1,
    material: "steel",
    color: 0xb08d57,
    blurb: "遅いが制御しやすい電動リフト。持ち上げて運ぶ。",
    damageMul: 0.6,
    selfDamageMul: 0.05,
    reach: 0.18,
    impulse: 650,
    cooldown: 1.7,
    sweep: 1.15,
    strokeSec: 0.25
  },
  {
    id: "spear-std",
    type: "spear",
    faces: IMPULSE_FACES,
    mechanism: "prismatic",
    launch: "punch",
    name: "Telescopic Spear",
    nameJa: "飛び出すスピア",
    category: "weapon",
    action: "triggered",
    effect: "impulse",
    slot: "primary",
    cost: 290,
    mass: 18,
    hp: 165,
    armor: 4,
    cells: [3, 2],
    height: 0.1,
    material: "steel",
    color: 0x8d9299,
    blurb: "油圧で突き出す槍。一点に穿つ。sweepは伸び量[m]。",
    damageMul: 1.5,
    selfDamageMul: 0.08,
    reach: 0.55,
    impulse: 900,
    cooldown: 2.1,
    sweep: 0.55,
    strokeSec: 0.13
  },
  {
    id: "axe-hammer",
    type: "hammer",
    faces: IMPULSE_FACES,
    mechanism: "revolute",
    launch: "punch",
    name: "Axe Hammer",
    nameJa: "アックス／ハンマー",
    category: "weapon",
    action: "triggered",
    effect: "impulse",
    slot: "primary",
    cost: 220,
    mass: 20,
    hp: 190,
    armor: 5,
    cells: [3, 3],
    height: 0.22,
    material: "steel",
    color: 0x7a2f20,
    blurb: "頭上から叩き込む斧／ハンマー。連打で装甲を割る。",
    damageMul: 1.4,
    selfDamageMul: 0.1,
    reach: 0.28,
    impulse: 700,
    cooldown: 1.6,
    sweep: 1.9,
    strokeSec: 0.2
  },
  {
    id: "crusher-jaws",
    type: "crusher",
    faces: IMPULSE_FACES,
    mechanism: "revolute",
    name: "Crusher Jaws",
    nameJa: "クラッシャー顎",
    category: "weapon",
    action: "triggered",
    effect: "clamp",
    slot: "secondary",
    cost: 340,
    mass: 28,
    hp: 230,
    armor: 8,
    cells: [4, 3],
    height: 0.14,
    material: "hardox",
    color: 0x3a3f45,
    blurb: "掴んで潰す油圧顎。保持中に装甲を噛み砕く。",
    damageMul: 1.0,
    selfDamageMul: 0.08,
    reach: 0.15,
    dps: 36,
    holdSec: 3.2,
    cooldown: 3.5
  },
  {
    id: "grabber-bar",
    type: "crusher",
    faces: IMPULSE_FACES,
    mechanism: "revolute",
    name: "Bar Grabber",
    nameJa: "バール型グラバー",
    category: "weapon",
    action: "triggered",
    effect: "clamp",
    slot: "secondary",
    cost: 200,
    mass: 16,
    hp: 160,
    armor: 5,
    cells: [3, 2],
    height: 0.12,
    material: "steel",
    color: 0xb08d57,
    blurb: "安価なバール型掴み。保持は短いが手軽に挟める。",
    damageMul: 0.85,
    selfDamageMul: 0.1,
    reach: 0.14,
    dps: 24,
    holdSec: 2.0,
    cooldown: 2.4
  },

  /* ======================== weapon: flame (2) ======================== */
  {
    id: "flamethrower",
    type: "flame",
    faces: IMPULSE_FACES,
    mechanism: "fixed",
    name: "Flamethrower",
    nameJa: "火炎放射器",
    category: "weapon",
    action: "held",
    effect: "flame",
    slot: "primary",
    cost: 280,
    mass: 17,
    hp: 110,
    armor: 2,
    cells: [3, 2],
    height: 0.12,
    material: "brass",
    color: 0xb08d57,
    blurb: "燃料式火炎放射。装甲をほぼ無視して燃やす。",
    damageMul: 1.0,
    selfDamageMul: 0,
    reach: 0.3,
    dps: 32,
    coneAngle: 0.38,
    coneRange: 2.6,
    fuel: 7.5,
    refuelRate: 0.3
  },
  {
    id: "burner-short",
    type: "flame",
    faces: IMPULSE_FACES,
    mechanism: "fixed",
    name: "Short Burner",
    nameJa: "短射程バーナー",
    category: "weapon",
    action: "held",
    effect: "flame",
    slot: "secondary",
    cost: 150,
    mass: 10,
    hp: 85,
    armor: 1,
    cells: [2, 2],
    height: 0.1,
    material: "brass",
    color: 0xb08d57,
    blurb: "安価な短射程バーナー。燃料は多め、届きは短い。",
    damageMul: 0.85,
    selfDamageMul: 0,
    reach: 0.18,
    dps: 26,
    coneAngle: 0.45,
    coneRange: 1.4,
    fuel: 12,
    refuelRate: 0.4
  },

  /* ======================== weapon: static (5) ======================== */
  {
    id: "wedge-std",
    type: "wedge",
    faces: STATIC_FACES,
    mechanism: "fixed",
    name: "Control Wedge",
    nameJa: "ウェッジ",
    category: "weapon",
    action: "passive",
    effect: "static",
    slot: "tertiary",
    cost: 90,
    mass: 12,
    hp: 260,
    armor: 18,
    cells: [5, 2],
    height: 0.08,
    material: "steel",
    color: 0x8d9299,
    blurb: "相手をすくい上げる制御ウェッジ。耐久と判定向き。",
    damageMul: 0.3,
    selfDamageMul: 0,
    reach: 0.16
  },
  {
    id: "forks-std",
    type: "fork",
    faces: STATIC_FACES,
    mechanism: "fixed",
    name: "Front Forks",
    nameJa: "フォーク",
    category: "weapon",
    action: "passive",
    effect: "static",
    slot: "tertiary",
    cost: 85,
    mass: 12,
    hp: 240,
    armor: 14,
    cells: [5, 2],
    height: 0.07,
    material: "steel",
    color: 0x8d9299,
    blurb: "相手の下に潜る前方フォーク。すくいと固定。",
    damageMul: 0.25,
    selfDamageMul: 0,
    reach: 0.2
  },
  {
    id: "spike-rack",
    type: "spike",
    faces: STATIC_FACES,
    mechanism: "fixed",
    name: "Spike Rack",
    nameJa: "スパイクラック",
    category: "weapon",
    action: "passive",
    effect: "static",
    slot: "tertiary",
    cost: 75,
    mass: 10,
    hp: 220,
    armor: 12,
    cells: [3, 2],
    height: 0.09,
    material: "steel",
    color: 0x2f3336,
    blurb: "固定スパイク列。体当たりの一点集中。",
    damageMul: 0.4,
    selfDamageMul: 0,
    reach: 0.12
  },
  {
    id: "wedge-ramp",
    type: "wedge",
    faces: STATIC_FACES,
    mechanism: "fixed",
    name: "Long Ramp Wedge",
    nameJa: "ランプウェッジ（長）",
    category: "weapon",
    action: "passive",
    effect: "static",
    slot: "tertiary",
    cost: 120,
    mass: 16,
    hp: 280,
    armor: 16,
    cells: [5, 3],
    height: 0.1,
    material: "steel",
    color: 0x8d9299,
    blurb: "長いランプ状ウェッジ。深く潜り安定してすくう。",
    damageMul: 0.28,
    selfDamageMul: 0,
    reach: 0.24
  },
  {
    id: "spike-horn",
    type: "spike",
    faces: STATIC_FACES,
    mechanism: "fixed",
    name: "Horn Spike",
    nameJa: "ホーンスパイク",
    category: "weapon",
    action: "passive",
    effect: "static",
    slot: "tertiary",
    cost: 95,
    mass: 11,
    hp: 200,
    armor: 10,
    cells: [2, 3],
    height: 0.14,
    material: "steel",
    color: 0x2f3336,
    blurb: "前方に突き出す角型スパイク。突進の貫通力。",
    damageMul: 0.55,
    selfDamageMul: 0,
    reach: 0.2
  },

  /* ======================== armor (10) ======================== */
  {
    id: "plate-steel",
    type: "plate",
    faces: ALL_FACES,
    name: "Steel Plate",
    nameJa: "鋼板",
    category: "armor",
    cost: 70,
    mass: 12,
    hp: 280,
    armor: 22,
    cells: [3, 2],
    height: 0.05,
    material: "steel",
    color: 0x8d9299,
    blurb: "安くて重い普通鋼板。コスト効率の防壁。"
  },
  {
    id: "plate-titanium",
    type: "plate",
    faces: ALL_FACES,
    name: "Titanium Plate",
    nameJa: "チタン板",
    category: "armor",
    cost: 160,
    mass: 6,
    hp: 260,
    armor: 20,
    cells: [3, 2],
    height: 0.04,
    material: "titanium",
    color: 0x8d9299,
    blurb: "軽くて高価なチタン板。機動を落とさず守る。"
  },
  {
    id: "armor-uhmw",
    type: "plate",
    faces: ALL_FACES,
    name: "UHMW Polymer",
    nameJa: "UHMWポリマー",
    category: "armor",
    cost: 110,
    mass: 8,
    hp: 220,
    armor: 14,
    cells: [3, 2],
    height: 0.06,
    material: "polymer",
    color: 0x2f3336,
    blurb: "スピナー衝撃を散らす超高分子ポリエチレン。",
    spinnerResist: 0.55
  },
  {
    id: "skirt-hardox",
    type: "skirt",
    faces: SKIRT_FACES,
    name: "Hardox Skirt",
    nameJa: "Hardoxスカート",
    category: "armor",
    cost: 100,
    mass: 10,
    hp: 250,
    armor: 20,
    cells: [1, 4],
    height: 0.05,
    material: "hardox",
    color: 0x3a3f45,
    blurb: "側面を覆うHardox製スカート。横槍を散らす。"
  },
  {
    id: "heat-shield",
    type: "plate",
    faces: ALL_FACES,
    name: "Heat Shield",
    nameJa: "耐熱シールド",
    category: "armor",
    cost: 120,
    mass: 9,
    hp: 200,
    armor: 12,
    cells: [3, 3],
    height: 0.05,
    material: "titanium",
    color: 0x7a2f20,
    blurb: "火炎と残火に効く耐熱シールド。",
    flameResist: 0.35
  },
  {
    id: "rail-anti-spinner",
    type: "plate",
    faces: ALL_FACES,
    name: "Anti-Spinner Rail",
    nameJa: "アンチスピナー・レール",
    category: "armor",
    cost: 130,
    mass: 11,
    hp: 240,
    armor: 18,
    cells: [4, 1],
    height: 0.06,
    material: "hardox",
    color: 0x2f3336,
    blurb: "スピナーを受け流す前面レール。",
    spinnerResist: 0.5
  },
  {
    id: "plate-ti-thin",
    type: "plate",
    faces: ALL_FACES,
    name: "Thin Titanium Sheet",
    nameJa: "チタン薄板",
    category: "armor",
    cost: 100,
    mass: 4,
    hp: 180,
    armor: 14,
    cells: [2, 2],
    height: 0.03,
    material: "titanium",
    color: 0x8d9299,
    blurb: "薄いチタン板。軽いが本格装甲より脆い。"
  },
  {
    id: "applique-light",
    type: "applique",
    faces: ALL_FACES,
    name: "Light Applique",
    nameJa: "軽量貼付装甲",
    category: "armor",
    cost: 28,
    mass: 2,
    hp: 95,
    armor: 7,
    cells: [2, 1],
    height: 0.02,
    material: "aluminium",
    color: 0x8d9299,
    blurb: "薄く安い貼付装甲。余った予算で弱点を塞ぐ。"
  },
  {
    id: "applique-mid",
    type: "applique",
    faces: ALL_FACES,
    name: "Mid Applique",
    nameJa: "中量貼付装甲",
    category: "armor",
    cost: 42,
    mass: 4,
    hp: 125,
    armor: 10,
    cells: [2, 2],
    height: 0.025,
    material: "steel",
    color: 0x8d9299,
    blurb: "標準サイズの貼付装甲。どの面にも貼れる。"
  },
  {
    id: "applique-edge",
    type: "applique",
    faces: ALL_FACES,
    name: "Edge Applique Strip",
    nameJa: "縁貼付装甲ストリップ",
    category: "armor",
    cost: 55,
    mass: 5,
    hp: 155,
    armor: 13,
    cells: [3, 1],
    height: 0.025,
    material: "hardox",
    color: 0x3a3f45,
    blurb: "縁に沿って貼るHardox薄帯。角の欠損を補修。"
  },

  /* ======================== utility (6) ======================== */
  {
    id: "util-self-right",
    type: "srimech",
    faces: UTIL_FACES,
    name: "Self-Right Module",
    nameJa: "セルフライト機構",
    category: "utility",
    cost: 120,
    mass: 6,
    hp: 80,
    armor: 2,
    cells: [2, 2],
    height: 0.08,
    material: "steel",
    color: 0xb08d57,
    blurb: "反転復帰を可能にする機構。クールダウンあり。",
    selfRight: true
  },
  {
    id: "util-power-cell",
    type: "power",
    faces: UTIL_FACES,
    name: "Power Cell",
    nameJa: "パワーセル",
    category: "utility",
    cost: 140,
    mass: 9,
    hp: 70,
    armor: 2,
    cells: [2, 2],
    height: 0.08,
    material: "brass",
    color: 0xe0a80d,
    blurb: "駆動トルクを底上げする高出力電源。",
    powerMul: 1.15
  },
  {
    id: "util-weapon-boost",
    type: "booster",
    faces: UTIL_FACES,
    name: "Weapon Booster",
    nameJa: "武器ブースター",
    category: "utility",
    cost: 160,
    mass: 8,
    hp: 75,
    armor: 2,
    cells: [2, 2],
    height: 0.08,
    material: "brass",
    color: 0xc8102e,
    blurb: "武器の加速トルクを底上げするブースター。",
    weaponPowerMul: 1.2
  },
  {
    id: "util-light-frame",
    type: "booster",
    faces: UTIL_FACES,
    name: "Lightweight Frame",
    nameJa: "軽量フレーム",
    category: "utility",
    cost: 90,
    mass: 5,
    hp: 65,
    armor: 1,
    cells: [2, 1],
    height: 0.04,
    material: "carbon",
    color: 0x2f3336,
    blurb: "炭素繊維の軽量補強。わずかな質量で剛性を足す。"
  },
  {
    id: "util-ballast",
    type: "power",
    faces: UTIL_FACES,
    name: "CG Ballast",
    nameJa: "重心バラスト",
    category: "utility",
    cost: 35,
    mass: 14,
    hp: 100,
    armor: 4,
    cells: [2, 2],
    height: 0.05,
    material: "steel",
    color: 0x3a3f45,
    blurb: "低重心用の鋼塊。機動は落ちるが転倒しにくい。"
  },
  {
    id: "util-spare-battery",
    type: "power",
    faces: UTIL_FACES,
    name: "Spare Battery",
    nameJa: "予備バッテリー",
    category: "utility",
    cost: 95,
    mass: 7,
    hp: 60,
    armor: 2,
    cells: [2, 1],
    height: 0.06,
    material: "brass",
    color: 0xe0a80d,
    blurb: "予備電源。パワーセルほどではないがトルクを足す。",
    powerMul: 1.08
  },

  /* ======================== EXTREME 枠（ネタ高額装備 ×12） ======================== */
  /* 強いのではなく極端。明確な代償つき。1500+予算でようやく1つ、3200で複数。 */
  {
    id: "bedrock-plate",
    type: "plate",
    faces: ALL_FACES,
    name: "Bedrock Plate",
    nameJa: "岩盤装甲",
    category: "armor",
    cost: 760,
    mass: 92,
    hp: 2500,
    armor: 90,
    cells: [5, 4],
    height: 0.12,
    material: "hardox",
    color: 0x3a3f45,
    blurb: "一歩も動けないが、まず壊れない。"
  },
  {
    id: "skypiercer",
    type: "spear",
    faces: IMPULSE_FACES,
    mechanism: "prismatic",
    launch: "punch",
    name: "Skypiercer",
    nameJa: "天突き",
    category: "weapon",
    action: "triggered",
    effect: "impulse",
    slot: "primary",
    cost: 640,
    mass: 20,
    hp: 85,
    armor: 2,
    cells: [4, 2],
    height: 0.1,
    material: "titanium",
    color: 0x8d9299,
    blurb: "届く。びっくりするほど届く。",
    damageMul: 1.6,
    selfDamageMul: 0.12,
    reach: 3.2,
    impulse: 950,
    cooldown: 5.0,
    sweep: 3.2,
    strokeSec: 0.22
  },
  {
    id: "overdrive-turbo",
    type: "booster",
    faces: UTIL_FACES,
    name: "Overdrive",
    nameJa: "暴走ターボ",
    category: "utility",
    cost: 560,
    mass: 4,
    hp: 45,
    armor: 1,
    cells: [2, 2],
    height: 0.07,
    material: "brass",
    color: 0xc8102e,
    blurb: "速すぎて曲がれない。",
    powerMul: 2.6
  },
  {
    id: "mooneater",
    type: "spinner",
    faces: SPINNER_FACES,
    mechanism: "revolute",
    spinAxis: "horizontal",
    name: "Mooneater",
    nameJa: "月喰い",
    category: "weapon",
    action: "passive",
    effect: "spin",
    slot: "primary",
    cost: 920,
    mass: 66,
    hp: 300,
    armor: 8,
    cells: [6, 3],
    height: 0.14,
    material: "hardox",
    color: 0xc8102e,
    blurb: "相手ごと自分も削る。",
    damageMul: 4.6,
    selfDamageMul: 0.5,
    reach: 0.35,
    maxOmega: 300,
    spinUpTorque: 90,
    inertia: 4.0
  },
  {
    id: "cathedral-saw",
    type: "saw",
    faces: SAW_DRILL_FACES,
    mechanism: "revolute",
    spinAxis: "horizontal",
    name: "Cathedral Saw",
    nameJa: "大車輪",
    category: "weapon",
    action: "passive",
    effect: "grind",
    slot: "tertiary",
    cost: 780,
    mass: 56,
    hp: 220,
    armor: 5,
    cells: [5, 5],
    height: 0.2,
    material: "hardox",
    color: 0xe0a80d,
    blurb: "機体より大きい円盤。寄れば道が開く。ただし重い。",
    damageMul: 1.8,
    selfDamageMul: 0.2,
    reach: 1.6,
    maxOmega: 160,
    spinUpTorque: 55,
    inertia: 2.8,
    dps: 78
  },
  {
    id: "dragon-breath",
    type: "flame",
    faces: IMPULSE_FACES,
    mechanism: "fixed",
    name: "Dragon Breath",
    nameJa: "竜の息",
    category: "weapon",
    action: "held",
    effect: "flame",
    slot: "secondary",
    cost: 680,
    mass: 24,
    hp: 100,
    armor: 2,
    cells: [3, 3],
    height: 0.14,
    material: "brass",
    color: 0x7a2f20,
    blurb: "竜の息。燃料は一瞬で尽きる。",
    damageMul: 1.2,
    selfDamageMul: 0,
    reach: 0.5,
    dps: 68,
    coneAngle: 0.42,
    coneRange: 5.0,
    fuel: 4.0,
    refuelRate: 0.15
  },
  {
    id: "final-curtain",
    type: "spear",
    faces: IMPULSE_FACES,
    mechanism: "prismatic",
    launch: "punch",
    name: "Final Curtain",
    nameJa: "終幕",
    category: "weapon",
    action: "triggered",
    effect: "impulse",
    slot: "primary",
    cost: 720,
    mass: 30,
    hp: 160,
    armor: 6,
    cells: [4, 2],
    height: 0.14,
    material: "hardox",
    color: 0x3a3f45,
    blurb: "終幕の一撃。外したら試合が終わる（あなたのほう）。",
    damageMul: 2.8,
    selfDamageMul: 0.15,
    reach: 0.55,
    impulse: 2700,
    cooldown: 9.0,
    sweep: 0.5,
    strokeSec: 0.08
  },
  {
    id: "immovable-anchor",
    type: "power",
    faces: UTIL_FACES,
    name: "Immovable Anchor",
    nameJa: "不動の錨",
    category: "utility",
    cost: 410,
    mass: 60,
    hp: 420,
    armor: 12,
    cells: [3, 3],
    height: 0.1,
    material: "steel",
    color: 0x3a3f45,
    blurb: "動かない。動かされない。ただ、それだけ。"
  },
  {
    id: "meteor-booster",
    type: "booster",
    faces: UTIL_FACES,
    name: "Meteor Booster",
    nameJa: "流星",
    category: "utility",
    cost: 600,
    mass: 14,
    hp: 70,
    armor: 2,
    cells: [2, 2],
    height: 0.1,
    material: "brass",
    color: 0xe0a80d,
    blurb: "流星の一押し。次の打ち上げまで長い。",
    powerMul: 2.7
  },
  {
    id: "feather-frame",
    type: "frame",
    faces: CHASSIS_FACES,
    name: "Feather Frame",
    nameJa: "羽根フレーム",
    category: "chassis",
    cost: 600,
    mass: 10,
    hp: 130,
    armor: 2,
    cells: [5, 6],
    deck: [5, 6],
    height: 0.07,
    heightCells: 2,
    groundClearance: 0.035,
    invertible: false,
    material: "carbon",
    color: 0x2f3336,
    blurb: "羽根のように軽い。紙のように破れる。",
    internalGrid: [3, 4],
    stockPowerKw: 2.0,
    stockAlternatorKw: 0.4,
    stockChargeKj: 3,
    stockFuelL: 2,
    stockCoolingKw: 1.2
  },
  {
    id: "twin-drill-auger",
    type: "drill",
    faces: SAW_DRILL_FACES,
    mechanism: "revolute",
    spinAxis: "horizontal",
    pairMount: true,
    name: "Twin Drill \"Auger\"",
    nameJa: "双錐オーガー",
    category: "weapon",
    action: "held",
    effect: "grind",
    slot: "primary",
    cost: 660,
    mass: 50,
    hp: 180,
    armor: 6,
    cells: [4, 3],
    height: 0.14,
    material: "hardox",
    color: 0x8d9299,
    blurb: "双錐で貫く。削るのは苦手、通すのが仕事。",
    damageMul: 3.7,
    selfDamageMul: 0.16,
    reach: 0.4,
    maxOmega: 70,
    spinUpTorque: 60,
    inertia: 1.4,
    dps: 11,
    fuel: 0
  },
  {
    id: "joker-plate",
    type: "applique",
    faces: ALL_FACES,
    name: "Joker Plate",
    nameJa: "落書き装甲",
    category: "armor",
    cost: 340,
    mass: 9,
    hp: 170,
    armor: 12,
    cells: [3, 2],
    height: 0.04,
    material: "aluminium",
    color: 0xc8102e,
    blurb: "見た目だけ派手。中身は落書き。高いのがネタ。"
  },

  /* ======================== internal plant (14) — engine bay only ======================== */
  {
    id: "eng-compact",
    type: "engine",
    faces: INTERNAL_FACES,
    name: "Compact Engine",
    nameJa: "コンパクト機関",
    category: "utility",
    cost: 60,
    mass: 8,
    hp: 55,
    armor: 1,
    cells: [2, 2],
    height: 0.07,
    material: "aluminium",
    color: 0x8d9299,
    blurb: "小型ESC一体機関。標準を少し超える入口。",
    powerKw: 3.0,
    alternatorKw: 0.8,
    heatMul: 1.0
  },
  {
    id: "eng-standard",
    type: "engine",
    faces: INTERNAL_FACES,
    name: "Standard Engine",
    nameJa: "標準機関",
    category: "utility",
    cost: 130,
    mass: 14,
    hp: 70,
    armor: 2,
    cells: [2, 3],
    height: 0.08,
    material: "steel",
    color: 0x8d9299,
    blurb: "汎用の中型機関。出力と発熱の基準点。",
    powerKw: 6.0,
    alternatorKw: 1.5,
    heatMul: 1.0
  },
  {
    id: "eng-heavy",
    type: "engine",
    faces: INTERNAL_FACES,
    name: "Heavy Engine",
    nameJa: "重量機関",
    category: "utility",
    cost: 240,
    mass: 24,
    hp: 90,
    armor: 3,
    cells: [3, 3],
    height: 0.1,
    material: "steel",
    color: 0x3a3f45,
    blurb: "厚肉クランクの大トルク機関。冷却を忘れずに。",
    powerKw: 11.0,
    alternatorKw: 2.5,
    heatMul: 1.1
  },
  {
    id: "eng-race",
    type: "engine",
    faces: INTERNAL_FACES,
    name: "Race Engine",
    nameJa: "レース機関",
    category: "utility",
    cost: 420,
    mass: 20,
    hp: 65,
    armor: 1,
    cells: [3, 3],
    height: 0.09,
    material: "titanium",
    color: 0xc8102e,
    blurb: "セル・kg当たり最高出力。一番熱い——冷却を積め。",
    powerKw: 18.0,
    alternatorKw: 3.0,
    heatMul: 1.6
  },
  {
    id: "eng-titan",
    type: "engine",
    faces: INTERNAL_FACES,
    name: "Titan Engine",
    nameJa: "タイタン機関",
    category: "utility",
    cost: 780,
    mass: 55,
    hp: 110,
    armor: 3,
    cells: [4, 3],
    height: 0.12,
    material: "hardox",
    color: 0x3a3f45,
    blurb: "4×3の巨体。軽量シャーシには物理的に入らない。",
    powerKw: 28.0,
    alternatorKw: 4.0,
    heatMul: 1.3
  },
  {
    id: "battery-small",
    type: "battery",
    faces: INTERNAL_FACES,
    name: "Small Battery",
    nameJa: "小型バッテリ",
    category: "utility",
    cost: 55,
    mass: 5,
    hp: 45,
    armor: 1,
    cells: [2, 1],
    height: 0.05,
    material: "polymer",
    color: 0x1b4a8f,
    blurb: "薄型パック。瞬間の電力不足を埋める。",
    chargeKj: 8
  },
  {
    id: "battery-std",
    type: "battery",
    faces: INTERNAL_FACES,
    name: "Standard Battery",
    nameJa: "標準バッテリ",
    category: "utility",
    cost: 110,
    mass: 9,
    hp: 55,
    armor: 1,
    cells: [2, 2],
    height: 0.06,
    material: "polymer",
    color: 0x1b4a8f,
    blurb: "主力パック。フリッパー連射の土台。",
    chargeKj: 18
  },
  {
    id: "battery-deep",
    type: "battery",
    faces: INTERNAL_FACES,
    name: "Deep-Cycle Battery",
    nameJa: "ディープサイクル",
    category: "utility",
    cost: 210,
    mass: 17,
    hp: 70,
    armor: 2,
    cells: [2, 3],
    height: 0.07,
    material: "polymer",
    color: 0x1b4a8f,
    blurb: "大容量。長試合でも電荷が枯れにくい。",
    chargeKj: 34
  },
  {
    id: "tank-small",
    type: "tank",
    faces: INTERNAL_FACES,
    name: "Small Fuel Tank",
    nameJa: "小型燃料タンク",
    category: "utility",
    cost: 45,
    mass: 6,
    hp: 40,
    armor: 1,
    cells: [2, 1],
    height: 0.05,
    material: "steel",
    color: 0x7a2f20,
    blurb: "予備燃料。火炎の点火を少し延ばす。",
    fuelL: 6
  },
  {
    id: "tank-std",
    type: "tank",
    faces: INTERNAL_FACES,
    name: "Standard Fuel Tank",
    nameJa: "標準燃料タンク",
    category: "utility",
    cost: 95,
    mass: 12,
    hp: 55,
    armor: 1,
    cells: [2, 2],
    height: 0.06,
    material: "steel",
    color: 0x7a2f20,
    blurb: "中型タンク。保持武器の主燃料庫。",
    fuelL: 14
  },
  {
    id: "tank-drum",
    type: "tank",
    faces: INTERNAL_FACES,
    name: "Drum Fuel Tank",
    nameJa: "ドラムタンク",
    category: "utility",
    cost: 190,
    mass: 24,
    hp: 75,
    armor: 2,
    cells: [3, 2],
    height: 0.08,
    material: "steel",
    color: 0x7a2f20,
    blurb: "大容量ドラム。火を長く吐くための体積。",
    fuelL: 30
  },
  {
    id: "rad-slim",
    type: "radiator",
    faces: INTERNAL_FACES,
    name: "Slim Radiator",
    nameJa: "薄型ラジエータ",
    category: "utility",
    cost: 50,
    mass: 4,
    hp: 40,
    armor: 1,
    cells: [2, 1],
    height: 0.04,
    material: "aluminium",
    color: 0xb08d57,
    blurb: "隙間に入る薄型冷却。レース機関の相棒。",
    coolingKw: 2.5
  },
  {
    id: "rad-std",
    type: "radiator",
    faces: INTERNAL_FACES,
    name: "Standard Radiator",
    nameJa: "標準ラジエータ",
    category: "utility",
    cost: 105,
    mass: 8,
    hp: 50,
    armor: 1,
    cells: [2, 2],
    height: 0.05,
    material: "aluminium",
    color: 0xb08d57,
    blurb: "標準冷却。熱ダレを抑える定番。",
    coolingKw: 5.0
  },
  {
    id: "rad-stack",
    type: "radiator",
    faces: INTERNAL_FACES,
    name: "Stacked Radiator",
    nameJa: "スタックラジエータ",
    category: "utility",
    cost: 200,
    mass: 15,
    hp: 65,
    armor: 2,
    cells: [3, 2],
    height: 0.07,
    material: "aluminium",
    color: 0xb08d57,
    blurb: "二重コアの大冷却。タイタン機関の熱を捌く。",
    coolingKw: 9.0
  }
];

/* ------------------------------------------------------------------ */
/* presets — v3: every PlacedPart has face; 8 bots; face-grid checks  */
/* ------------------------------------------------------------------ */

export const PRESETS: readonly BotSpec[] = [
  // spin-king — chassis-medium deck 7×9 / heightCells 3
  // faces:
  //   underside: wheel-mid×4 @ (0,2)(5,2)(0,6)(5,6)  each 2×2 — no overlap
  //   deck: disc-heavy 5×2 @ (1,0); plate-steel 3×2 @ (2,4); util-self-right 2×2 @ (2,7)
  // cost: 160 + 45×4 + 380 + 70 + 120 = 910 ≤ 1000
  // mass: 32 + 8×4 + 30 + 12 + 6 = 112 kg
  // drive×4 / primary disc / no secondary / all faces allowed
  {
    v: 3,
    name: "spin-king",
    chassisId: "chassis-medium",
    paint: 0xc8102e,
    parts: [
      { partId: "wheel-mid", face: "underside", cell: [0, 2], rot: 0 },
      { partId: "wheel-mid", face: "underside", cell: [5, 2], rot: 0 },
      { partId: "wheel-mid", face: "underside", cell: [0, 6], rot: 0 },
      { partId: "wheel-mid", face: "underside", cell: [5, 6], rot: 0 },
      { partId: "disc-heavy", face: "deck", cell: [1, 0], rot: 0 },
      { partId: "plate-steel", face: "deck", cell: [2, 4], rot: 0 },
      { partId: "util-self-right", face: "deck", cell: [2, 7], rot: 0 }
    ]
  },

  // flip-jack — chassis-medium 7×9 / h3
  //   underside: wheel-grip×4 @ (0,3)(5,3)(0,5)(5,5) 2×2
  //   front (7×3): flipper-std 4×3 @ (1,0) — fills y fully
  //   rear  (7×3): wedge-std 5×2 @ (1,0)
  //   deck: util-self-right 2×2 @ (2,3)
  // cost: 160 + 48×4 + 320 + 90 + 120 = 882
  // mass: 32 + 7×4 + 25 + 12 + 6 = 103 kg
  {
    v: 3,
    name: "flip-jack",
    chassisId: "chassis-medium",
    paint: 0xe0a80d,
    parts: [
      { partId: "wheel-grip", face: "underside", cell: [0, 3], rot: 0 },
      { partId: "wheel-grip", face: "underside", cell: [5, 3], rot: 0 },
      { partId: "wheel-grip", face: "underside", cell: [0, 5], rot: 0 },
      { partId: "wheel-grip", face: "underside", cell: [5, 5], rot: 0 },
      { partId: "flipper-std", face: "front", cell: [1, 0], rot: 0 },
      { partId: "wedge-std", face: "rear", cell: [1, 0], rot: 0 },
      { partId: "util-self-right", face: "deck", cell: [2, 3], rot: 0 }
    ]
  },

  // brick-wall — chassis-heavy 9×11 / h4
  //   left  (11×4): track-std 2×4 @ (3,0)
  //   right (11×4): track-std 2×4 @ (3,0)
  //   front (9×4):  wedge-std 5×2 @ (2,0)  [tertiary static]
  //   deck: cutting-disc 2×2 @ (3,2) [secondary]; plate-steel 3×2 @ (3,6); armor-uhmw 3×2 @ (3,8)
  //   (side-saws→tertiary と wedge が同スロット衝突するため cutting-disc に差し替え)
  // cost: 230 + 90×2 + 200 + 90 + 70 + 110 = 880
  // mass: 48 + 16×2 + 12 + 12 + 12 + 8 = 124 kg
  {
    v: 3,
    name: "brick-wall",
    chassisId: "chassis-heavy",
    paint: 0x8d9299,
    parts: [
      { partId: "track-std", face: "left", cell: [3, 0], rot: 0 },
      { partId: "track-std", face: "right", cell: [3, 0], rot: 0 },
      { partId: "cutting-disc", face: "deck", cell: [3, 2], rot: 0 },
      { partId: "wedge-std", face: "front", cell: [2, 0], rot: 0 },
      { partId: "plate-steel", face: "deck", cell: [3, 6], rot: 0 },
      { partId: "armor-uhmw", face: "deck", cell: [3, 8], rot: 0 }
    ]
  },

  // drum-runner — chassis-light 5×7 / h3
  //   underside: wheel-small×4 @ (0,3)(4,3)(0,6)(4,6) 1×1
  //   front (5×3): drum-std 4×3 @ (0,0)
  //   deck: util-power-cell 2×2 @ (1,4); util-light-frame 2×1 @ (1,6)
  // cost: 110 + 40×4 + 340 + 140 + 90 = 840
  // mass: 20 + 4×4 + 32 + 9 + 5 = 82 kg
  {
    v: 3,
    name: "drum-runner",
    chassisId: "chassis-light",
    paint: 0x1b4a8f,
    parts: [
      { partId: "wheel-small", face: "underside", cell: [0, 3], rot: 0 },
      { partId: "wheel-small", face: "underside", cell: [4, 3], rot: 0 },
      { partId: "wheel-small", face: "underside", cell: [0, 6], rot: 0 },
      { partId: "wheel-small", face: "underside", cell: [4, 6], rot: 0 },
      { partId: "drum-std", face: "front", cell: [0, 0], rot: 0 },
      { partId: "util-power-cell", face: "deck", cell: [1, 4], rot: 0 },
      { partId: "util-light-frame", face: "deck", cell: [1, 6], rot: 0 }
    ]
  },

  // pyro — chassis-medium 7×9 / h3
  //   underside: wheel-mid×4 @ (0,1)(5,1)(0,5)(5,5)
  //   front (7×3): flamethrower 3×2 @ (2,0)
  //   rear  (7×3): forks-std 5×2 @ (1,0)
  //   deck: heat-shield 3×3 @ (2,3)
  // cost: 160 + 45×4 + 280 + 85 + 120 = 825
  // mass: 32 + 8×4 + 17 + 12 + 9 = 102 kg
  {
    v: 3,
    name: "pyro",
    chassisId: "chassis-medium",
    paint: 0x7a2f20,
    parts: [
      { partId: "wheel-mid", face: "underside", cell: [0, 1], rot: 0 },
      { partId: "wheel-mid", face: "underside", cell: [5, 1], rot: 0 },
      { partId: "wheel-mid", face: "underside", cell: [0, 5], rot: 0 },
      { partId: "wheel-mid", face: "underside", cell: [5, 5], rot: 0 },
      { partId: "flamethrower", face: "front", cell: [2, 0], rot: 0 },
      { partId: "forks-std", face: "rear", cell: [1, 0], rot: 0 },
      { partId: "heat-shield", face: "deck", cell: [2, 3], rot: 0 }
    ]
  },

  // impaler — chassis-medium 7×9 / h3
  //   underside: wheel-mid×4 @ (0,5)(5,5)(0,7)(5,7)
  //   front (7×3): spear-std 3×2 @ (2,0)
  //   deck: crusher-jaws 4×3 @ (1,2)
  // cost: 160 + 45×4 + 290 + 340 = 970
  // mass: 32 + 8×4 + 18 + 28 = 110 kg
  {
    v: 3,
    name: "impaler",
    chassisId: "chassis-medium",
    paint: 0x3a3f45,
    parts: [
      { partId: "wheel-mid", face: "underside", cell: [0, 5], rot: 0 },
      { partId: "wheel-mid", face: "underside", cell: [5, 5], rot: 0 },
      { partId: "wheel-mid", face: "underside", cell: [0, 7], rot: 0 },
      { partId: "wheel-mid", face: "underside", cell: [5, 7], rot: 0 },
      { partId: "spear-std", face: "front", cell: [2, 0], rot: 0 },
      { partId: "crusher-jaws", face: "deck", cell: [1, 2], rot: 0 }
    ]
  },

  // driller — chassis-medium 7×9 / h3
  //   left  (9×3): wheel-mid 2×2 @ (1,0); wheel-mid 2×2 @ (5,0)
  //   right (9×3): wheel-mid 2×2 @ (1,0); wheel-mid 2×2 @ (5,0)
  //   front (7×3): drill-twin 3×2 @ (2,0)
  //   deck: applique-mid 2×2 @ (2,4); util-spare-battery 2×1 @ (2,7)
  // cost: 160 + 45×4 + 280 + 42 + 95 = 757
  // mass: 32 + 8×4 + 20 + 4 + 7 = 95 kg
  {
    v: 3,
    name: "driller",
    chassisId: "chassis-medium",
    paint: 0x1b4a8f,
    parts: [
      { partId: "wheel-mid", face: "left", cell: [1, 0], rot: 0 },
      { partId: "wheel-mid", face: "left", cell: [5, 0], rot: 0 },
      { partId: "wheel-mid", face: "right", cell: [1, 0], rot: 0 },
      { partId: "wheel-mid", face: "right", cell: [5, 0], rot: 0 },
      { partId: "drill-twin", face: "front", cell: [2, 0], rot: 0 },
      { partId: "applique-mid", face: "deck", cell: [2, 4], rot: 0 },
      { partId: "util-spare-battery", face: "deck", cell: [2, 7], rot: 0 }
    ]
  },

  // shredder — chassis-medium 7×9 / h3
  //   underside: wheel-small×4 @ (0,2)(6,2)(0,6)(6,6) 1×1
  //   left  (9×3): side-saws 2×2 @ (3,0)
  //   right (9×3): angle-grinder 2×2 @ (3,0)  [secondary grind]
  //   deck: applique-light 2×1 @ (2,0); plate-ti-thin 2×2 @ (2,4)
  // cost: 160 + 40×4 + 180 + 130 + 28 + 100 = 758
  // mass: 32 + 4×4 + 13 + 10 + 2 + 4 = 77 kg
  // note: side-saws tertiary, angle-grinder secondary — one each slot
  {
    v: 3,
    name: "shredder",
    chassisId: "chassis-medium",
    paint: 0xc8102e,
    parts: [
      { partId: "wheel-small", face: "underside", cell: [0, 2], rot: 0 },
      { partId: "wheel-small", face: "underside", cell: [6, 2], rot: 0 },
      { partId: "wheel-small", face: "underside", cell: [0, 6], rot: 0 },
      { partId: "wheel-small", face: "underside", cell: [6, 6], rot: 0 },
      { partId: "side-saws", face: "left", cell: [3, 0], rot: 0 },
      { partId: "angle-grinder", face: "right", cell: [3, 0], rot: 0 },
      { partId: "applique-light", face: "deck", cell: [2, 0], rot: 0 },
      { partId: "plate-ti-thin", face: "deck", cell: [2, 4], rot: 0 }
    ]
  }
];

export function buildCatalog(): Catalog {
  const byId = new Map<string, PartDef>();
  for (const part of PARTS) {
    byId.set(part.id, part);
  }
  return {
    parts: PARTS,
    presets: PRESETS,
    byId
  };
}
