import type { CardDef } from "../engine/types";

// Balance: e1 ≈ dmg5/block5/move2/draw1; e2 ≈ ×2.2; e3 ≈ ×3.5.
// textJa must match effects. combatOnly = attack/block; overworldOnly = move.

export const CARDS: Record<string, CardDef> = {
  // ── Knight (10) ───────────────────────────────────────────────────────────
  "knight-strike": {
    id: "knight-strike",
    name: "Brick Strike",
    nameJa: "ブリック打撃",
    kind: "attack",
    cls: "knight",
    energy: 1,
    price: 0,
    rarity: 0,
    textJa: "5ダメージ",
    effects: [{ t: "dmg", n: 5 }],
    combatOnly: true,
  },
  "knight-guard": {
    id: "knight-guard",
    name: "Stud Guard",
    nameJa: "スタッドガード",
    kind: "skill",
    cls: "knight",
    energy: 1,
    price: 0,
    rarity: 0,
    textJa: "5ブロック",
    effects: [{ t: "block", n: 5 }],
    combatOnly: true,
  },
  "knight-charge": {
    id: "knight-charge",
    name: "Plate Charge",
    nameJa: "プレート突撃",
    kind: "attack",
    cls: "knight",
    energy: 1,
    price: 0,
    rarity: 0,
    textJa: "4ダメージ・1ブロック",
    effects: [
      { t: "dmg", n: 4 },
      { t: "block", n: 1 },
    ],
    combatOnly: true,
  },
  "knight-shield-bash": {
    id: "knight-shield-bash",
    name: "Shield Bash",
    nameJa: "盾殴り",
    kind: "attack",
    cls: "knight",
    energy: 2,
    price: 0,
    rarity: 1,
    textJa: "6ダメージ・5ブロック",
    effects: [
      { t: "dmg", n: 6 },
      { t: "block", n: 5 },
    ],
    combatOnly: true,
  },
  "knight-fortify": {
    id: "knight-fortify",
    name: "Fortify",
    nameJa: "要塞化",
    kind: "skill",
    cls: "knight",
    energy: 2,
    price: 0,
    rarity: 1,
    textJa: "11ブロック",
    effects: [{ t: "block", n: 11 }],
    combatOnly: true,
  },
  "knight-smite": {
    id: "knight-smite",
    name: "Brick Smite",
    nameJa: "断罪の一撃",
    kind: "attack",
    cls: "knight",
    energy: 2,
    price: 0,
    rarity: 1,
    textJa: "11ダメージ",
    effects: [{ t: "dmg", n: 11 }],
    combatOnly: true,
  },
  "knight-bulwark": {
    id: "knight-bulwark",
    name: "Bulwark",
    nameJa: "堅塁",
    kind: "skill",
    cls: "knight",
    energy: 2,
    price: 0,
    rarity: 1,
    textJa: "6ブロック・防御+2(2T)",
    effects: [
      { t: "block", n: 6 },
      { t: "buffDef", n: 2, turns: 2 },
    ],
    combatOnly: true,
  },
  "knight-rally": {
    id: "knight-rally",
    name: "Rally",
    nameJa: "鼓舞",
    kind: "skill",
    cls: "knight",
    energy: 1,
    price: 0,
    rarity: 1,
    textJa: "HP3回復・2ブロック",
    effects: [
      { t: "heal", n: 3 },
      { t: "block", n: 2 },
    ],
    combatOnly: true,
  },
  "knight-crush": {
    id: "knight-crush",
    name: "Crush",
    nameJa: "粉砕",
    kind: "attack",
    cls: "knight",
    energy: 3,
    price: 0,
    rarity: 2,
    textJa: "17ダメージ",
    effects: [{ t: "dmg", n: 17 }],
    combatOnly: true,
  },
  "knight-aegis": {
    id: "knight-aegis",
    name: "Aegis",
    nameJa: "イージス",
    kind: "skill",
    cls: "knight",
    energy: 3,
    price: 0,
    rarity: 2,
    textJa: "14ブロック・防御+2(2T)",
    effects: [
      { t: "block", n: 14 },
      { t: "buffDef", n: 2, turns: 2 },
    ],
    combatOnly: true,
  },

  // ── Rogue (10) ────────────────────────────────────────────────────────────
  "rogue-stab": {
    id: "rogue-stab",
    name: "Quick Stab",
    nameJa: "速刺し",
    kind: "attack",
    cls: "rogue",
    energy: 1,
    price: 0,
    rarity: 0,
    textJa: "5ダメージ",
    effects: [{ t: "dmg", n: 5 }],
    combatOnly: true,
  },
  "rogue-dash": {
    id: "rogue-dash",
    name: "Brick Dash",
    nameJa: "ダッシュ",
    kind: "action",
    cls: "rogue",
    energy: 1,
    price: 0,
    rarity: 0,
    textJa: "移動2",
    effects: [{ t: "move", n: 2 }],
    overworldOnly: true,
  },
  "rogue-feint": {
    id: "rogue-feint",
    name: "Feint",
    nameJa: "フェイント",
    kind: "skill",
    cls: "rogue",
    energy: 1,
    price: 0,
    rarity: 0,
    textJa: "2ブロック・1枚ドロー",
    effects: [
      { t: "block", n: 2 },
      { t: "draw", n: 1 },
    ],
    combatOnly: true,
  },
  "rogue-poison-blade": {
    id: "rogue-poison-blade",
    name: "Poison Blade",
    nameJa: "毒の刃",
    kind: "attack",
    cls: "rogue",
    energy: 1,
    price: 0,
    rarity: 1,
    textJa: "3ダメージ・毒2(2T)",
    effects: [
      { t: "dmg", n: 3 },
      { t: "poison", n: 2, turns: 2 },
    ],
    combatOnly: true,
  },
  "rogue-backstab": {
    id: "rogue-backstab",
    name: "Backstab",
    nameJa: "背刺し",
    kind: "attack",
    cls: "rogue",
    energy: 2,
    price: 0,
    rarity: 1,
    textJa: "11ダメージ",
    effects: [{ t: "dmg", n: 11 }],
    combatOnly: true,
  },
  "rogue-pickpocket": {
    id: "rogue-pickpocket",
    name: "Pickpocket",
    nameJa: "スリ",
    kind: "action",
    cls: "rogue",
    energy: 1,
    price: 0,
    rarity: 1,
    textJa: "コイン4",
    effects: [{ t: "gold", n: 4 }],
  },
  "rogue-shadow-step": {
    id: "rogue-shadow-step",
    name: "Shadow Step",
    nameJa: "影歩き",
    kind: "action",
    cls: "rogue",
    energy: 2,
    price: 0,
    rarity: 1,
    textJa: "移動3・山札の上2枚を確認し、呪いを底へ送る",
    effects: [
      { t: "move", n: 3 },
      { t: "scry", n: 2 },
    ],
    overworldOnly: true,
  },
  "rogue-twin-fangs": {
    id: "rogue-twin-fangs",
    name: "Twin Fangs",
    nameJa: "双牙",
    kind: "attack",
    cls: "rogue",
    energy: 2,
    price: 0,
    rarity: 1,
    textJa: "5ダメージ×2",
    effects: [{ t: "dmg", n: 5, times: 2 }],
    combatOnly: true,
  },
  "rogue-assassinate": {
    id: "rogue-assassinate",
    name: "Assassinate",
    nameJa: "暗殺",
    kind: "attack",
    cls: "rogue",
    energy: 3,
    price: 0,
    rarity: 2,
    textJa: "15ダメージ・貫通",
    effects: [{ t: "dmg", n: 15, pierce: true }],
    combatOnly: true,
  },
  "rogue-smoke-veil": {
    id: "rogue-smoke-veil",
    name: "Smoke Veil",
    nameJa: "煙幕",
    kind: "skill",
    cls: "rogue",
    energy: 2,
    price: 0,
    rarity: 2,
    textJa: "8ブロック・毒2(2T)",
    effects: [
      { t: "block", n: 8 },
      { t: "poison", n: 2, turns: 2 },
    ],
    combatOnly: true,
  },

  // ── Mage (10) ─────────────────────────────────────────────────────────────
  "mage-spark": {
    id: "mage-spark",
    name: "Spark",
    nameJa: "スパーク",
    kind: "attack",
    cls: "mage",
    energy: 1,
    price: 0,
    rarity: 0,
    textJa: "5ダメージ",
    effects: [{ t: "dmg", n: 5 }],
    combatOnly: true,
  },
  "mage-ward": {
    id: "mage-ward",
    name: "Arcane Ward",
    nameJa: "魔防壁",
    kind: "skill",
    cls: "mage",
    energy: 1,
    price: 0,
    rarity: 0,
    textJa: "5ブロック",
    effects: [{ t: "block", n: 5 }],
    combatOnly: true,
  },
  "mage-focus": {
    id: "mage-focus",
    name: "Focus",
    nameJa: "集中",
    kind: "skill",
    cls: "mage",
    energy: 0,
    price: 0,
    rarity: 0,
    textJa: "エネルギー1・このカード除去",
    effects: [{ t: "energy", n: 1 }, { t: "exhaust" }],
  },
  "mage-bolt": {
    id: "mage-bolt",
    name: "Mana Bolt",
    nameJa: "魔力弾",
    kind: "attack",
    cls: "mage",
    energy: 2,
    price: 0,
    rarity: 1,
    textJa: "11ダメージ",
    effects: [{ t: "dmg", n: 11 }],
    combatOnly: true,
  },
  "mage-frost": {
    id: "mage-frost",
    name: "Frost Snap",
    nameJa: "氷結",
    kind: "attack",
    cls: "mage",
    energy: 2,
    price: 0,
    rarity: 1,
    textJa: "6ダメージ・気絶1・このカード除去",
    effects: [
      { t: "dmg", n: 6 },
      { t: "stun", turns: 1 },
      { t: "exhaust" },
    ],
    combatOnly: true,
  },
  "mage-arcane-sight": {
    id: "mage-arcane-sight",
    name: "Arcane Sight",
    nameJa: "魔眼",
    kind: "skill",
    cls: "mage",
    energy: 1,
    price: 0,
    rarity: 1,
    textJa: "山札の上2枚を確認し、呪いを底へ送る",
    effects: [{ t: "scry", n: 2 }],
  },
  "mage-mana-surge": {
    id: "mage-mana-surge",
    name: "Mana Surge",
    nameJa: "魔力奔流",
    kind: "skill",
    cls: "mage",
    energy: 1,
    price: 0,
    rarity: 1,
    textJa: "エネルギー2",
    effects: [{ t: "energy", n: 2 }],
  },
  "mage-shatter": {
    id: "mage-shatter",
    name: "Shatter",
    nameJa: "破砕",
    kind: "attack",
    cls: "mage",
    energy: 2,
    price: 0,
    rarity: 1,
    textJa: "9ダメージ・貫通",
    effects: [{ t: "dmg", n: 9, pierce: true }],
    combatOnly: true,
  },
  "mage-fireball": {
    id: "mage-fireball",
    name: "Fireball",
    nameJa: "ファイアボール",
    kind: "attack",
    cls: "mage",
    energy: 3,
    price: 0,
    rarity: 2,
    textJa: "17ダメージ",
    effects: [{ t: "dmg", n: 17 }],
    combatOnly: true,
  },
  "mage-nova": {
    id: "mage-nova",
    name: "Nova",
    nameJa: "ノヴァ",
    kind: "attack",
    cls: "mage",
    energy: 3,
    price: 0,
    rarity: 2,
    textJa: "8ダメージ×2・攻撃+2(1T)",
    effects: [
      { t: "dmg", n: 8, times: 2 },
      { t: "buffAtk", n: 2, turns: 1 },
    ],
    combatOnly: true,
  },

  // ── Cleric (10) ───────────────────────────────────────────────────────────
  "cleric-smite": {
    id: "cleric-smite",
    name: "Holy Smite",
    nameJa: "聖打",
    kind: "attack",
    cls: "cleric",
    energy: 1,
    price: 0,
    rarity: 0,
    textJa: "5ダメージ",
    effects: [{ t: "dmg", n: 5 }],
    combatOnly: true,
  },
  "cleric-mend": {
    id: "cleric-mend",
    name: "Mend",
    nameJa: "修復",
    kind: "skill",
    cls: "cleric",
    energy: 1,
    price: 0,
    rarity: 0,
    textJa: "HP4回復",
    effects: [{ t: "heal", n: 4 }],
  },
  "cleric-barrier": {
    id: "cleric-barrier",
    name: "Sacred Barrier",
    nameJa: "聖障壁",
    kind: "skill",
    cls: "cleric",
    energy: 1,
    price: 0,
    rarity: 0,
    textJa: "5ブロック",
    effects: [{ t: "block", n: 5 }],
    combatOnly: true,
  },
  "cleric-bless": {
    id: "cleric-bless",
    name: "Bless",
    nameJa: "祝福",
    kind: "skill",
    cls: "cleric",
    energy: 1,
    price: 0,
    rarity: 1,
    textJa: "攻撃+3(2T)",
    effects: [{ t: "buffAtk", n: 3, turns: 2 }],
  },
  "cleric-holy-light": {
    id: "cleric-holy-light",
    name: "Holy Light",
    nameJa: "聖光",
    kind: "skill",
    cls: "cleric",
    energy: 2,
    price: 0,
    rarity: 1,
    textJa: "HP8回復",
    effects: [{ t: "heal", n: 8 }],
  },
  "cleric-sanctuary": {
    id: "cleric-sanctuary",
    name: "Sanctuary",
    nameJa: "聖域",
    kind: "skill",
    cls: "cleric",
    energy: 2,
    price: 0,
    rarity: 1,
    textJa: "6ブロック・HP4回復",
    effects: [
      { t: "block", n: 6 },
      { t: "heal", n: 4 },
    ],
    combatOnly: true,
  },
  "cleric-purge": {
    id: "cleric-purge",
    name: "Purge",
    nameJa: "浄化",
    kind: "attack",
    cls: "cleric",
    energy: 2,
    price: 0,
    rarity: 1,
    textJa: "8ダメージ・貫通",
    effects: [{ t: "dmg", n: 8, pierce: true }],
    combatOnly: true,
  },
  "cleric-divine-shield": {
    id: "cleric-divine-shield",
    name: "Divine Shield",
    nameJa: "神盾",
    kind: "skill",
    cls: "cleric",
    energy: 2,
    price: 0,
    rarity: 1,
    textJa: "8ブロック・防御+2(2T)",
    effects: [
      { t: "block", n: 8 },
      { t: "buffDef", n: 2, turns: 2 },
    ],
    combatOnly: true,
  },
  "cleric-judgement": {
    id: "cleric-judgement",
    name: "Judgement",
    nameJa: "審判",
    kind: "attack",
    cls: "cleric",
    energy: 3,
    price: 0,
    rarity: 2,
    textJa: "14ダメージ・HP3回復",
    effects: [
      { t: "dmg", n: 14 },
      { t: "heal", n: 3 },
    ],
    combatOnly: true,
  },
  "cleric-beacon": {
    id: "cleric-beacon",
    name: "Beacon",
    nameJa: "導きの灯",
    kind: "skill",
    cls: "cleric",
    energy: 2,
    price: 0,
    rarity: 2,
    textJa: "HP5回復・1枚ドロー",
    effects: [
      { t: "heal", n: 5 },
      { t: "draw", n: 1 },
    ],
  },

  // ── Neutral (~30) ─────────────────────────────────────────────────────────
  // Move
  stride: {
    id: "stride",
    name: "Stride",
    nameJa: "歩み",
    kind: "action",
    cls: "neutral",
    energy: 1,
    price: 4,
    rarity: 0,
    textJa: "移動2",
    effects: [{ t: "move", n: 2 }],
    overworldOnly: true,
  },
  sprint: {
    id: "sprint",
    name: "Sprint",
    nameJa: "疾走",
    kind: "action",
    cls: "neutral",
    energy: 2,
    price: 8,
    rarity: 1,
    textJa: "移動4",
    effects: [{ t: "move", n: 4 }],
    overworldOnly: true,
  },
  "long-march": {
    id: "long-march",
    name: "Long March",
    nameJa: "長征",
    kind: "action",
    cls: "neutral",
    energy: 3,
    price: 12,
    rarity: 2,
    textJa: "移動7",
    effects: [{ t: "move", n: 7 }],
    overworldOnly: true,
  },
  "camp-recall": {
    id: "camp-recall",
    name: "Camp Recall",
    nameJa: "野営帰還",
    kind: "action",
    cls: "neutral",
    energy: 2,
    price: 10,
    rarity: 1,
    textJa: "最寄り野営へ転移",
    effects: [{ t: "teleportCamp" }],
    overworldOnly: true,
  },
  "careful-step": {
    id: "careful-step",
    name: "Careful Step",
    nameJa: "慎重な一歩",
    kind: "action",
    cls: "neutral",
    energy: 0,
    price: 5,
    rarity: 0,
    textJa: "移動1",
    effects: [{ t: "move", n: 1 }],
    overworldOnly: true,
  },
  "pathfinder": {
    id: "pathfinder",
    name: "Pathfinder",
    nameJa: "道探し",
    kind: "action",
    cls: "neutral",
    energy: 1,
    price: 6,
    rarity: 1,
    textJa: "移動1・山札の上2枚を確認し、呪いを底へ送る",
    effects: [
      { t: "move", n: 1 },
      { t: "scry", n: 2 },
    ],
    overworldOnly: true,
  },

  // Economy
  "coin-purse": {
    id: "coin-purse",
    name: "Coin Purse",
    nameJa: "小銭入れ",
    kind: "action",
    cls: "neutral",
    energy: 1,
    price: 0,
    rarity: 0,
    textJa: "コイン3",
    effects: [{ t: "gold", n: 3 }],
  },
  "treasure-map": {
    id: "treasure-map",
    name: "Treasure Map",
    nameJa: "宝の地図",
    kind: "action",
    cls: "neutral",
    energy: 2,
    price: 9,
    rarity: 1,
    textJa: "コイン7",
    effects: [{ t: "gold", n: 7 }],
  },
  scavenger: {
    id: "scavenger",
    name: "Scavenger",
    nameJa: "拾い集め",
    kind: "action",
    cls: "neutral",
    energy: 1,
    price: 6,
    rarity: 1,
    textJa: "コイン1・1枚ドロー",
    effects: [
      { t: "gold", n: 1 },
      { t: "draw", n: 1 },
    ],
  },
  "bribe-bag": {
    id: "bribe-bag",
    name: "Bribe Bag",
    nameJa: "賄賂袋",
    kind: "action",
    cls: "neutral",
    energy: 2,
    price: 8,
    rarity: 1,
    textJa: "コイン5・XP2",
    effects: [
      { t: "gold", n: 5 },
      { t: "xp", n: 2 },
    ],
  },

  // Draw / scry
  study: {
    id: "study",
    name: "Study",
    nameJa: "学習",
    kind: "skill",
    cls: "neutral",
    energy: 1,
    price: 5,
    rarity: 0,
    textJa: "1枚ドロー",
    effects: [{ t: "draw", n: 1 }],
  },
  "deep-think": {
    id: "deep-think",
    name: "Deep Think",
    nameJa: "熟考",
    kind: "skill",
    cls: "neutral",
    energy: 2,
    price: 9,
    rarity: 1,
    textJa: "2枚ドロー",
    effects: [{ t: "draw", n: 2 }],
  },
  insight: {
    id: "insight",
    name: "Insight",
    nameJa: "洞察",
    kind: "skill",
    cls: "neutral",
    energy: 1,
    price: 6,
    rarity: 0,
    textJa: "山札の上2枚を確認し、呪いを底へ送る",
    effects: [{ t: "scry", n: 2 }],
  },
  research: {
    id: "research",
    name: "Research",
    nameJa: "研究",
    kind: "skill",
    cls: "neutral",
    energy: 2,
    price: 10,
    rarity: 1,
    textJa: "山札の上3枚を確認し、呪いを底へ送る・1枚ドロー",
    effects: [
      { t: "scry", n: 3 },
      { t: "draw", n: 1 },
    ],
  },
  "card-catalog": {
    id: "card-catalog",
    name: "Card Catalog",
    nameJa: "目録",
    kind: "skill",
    cls: "neutral",
    energy: 0,
    price: 7,
    rarity: 1,
    textJa: "1枚ドロー・このカード除去",
    effects: [{ t: "draw", n: 1 }, { t: "exhaust" }],
  },

  // Combat basics / utility
  jab: {
    id: "jab",
    name: "Jab",
    nameJa: "ジャブ",
    kind: "attack",
    cls: "neutral",
    energy: 1,
    price: 4,
    rarity: 0,
    textJa: "5ダメージ",
    effects: [{ t: "dmg", n: 5 }],
    combatOnly: true,
  },
  brace: {
    id: "brace",
    name: "Brace",
    nameJa: "構える",
    kind: "skill",
    cls: "neutral",
    energy: 1,
    price: 4,
    rarity: 0,
    textJa: "5ブロック",
    effects: [{ t: "block", n: 5 }],
    combatOnly: true,
  },
  "heavy-blow": {
    id: "heavy-blow",
    name: "Heavy Blow",
    nameJa: "重撃",
    kind: "attack",
    cls: "neutral",
    energy: 2,
    price: 8,
    rarity: 1,
    textJa: "11ダメージ",
    effects: [{ t: "dmg", n: 11 }],
    combatOnly: true,
  },
  "iron-wall": {
    id: "iron-wall",
    name: "Iron Wall",
    nameJa: "鉄壁",
    kind: "skill",
    cls: "neutral",
    energy: 2,
    price: 8,
    rarity: 1,
    textJa: "11ブロック",
    effects: [{ t: "block", n: 11 }],
    combatOnly: true,
  },
  "first-aid": {
    id: "first-aid",
    name: "First Aid",
    nameJa: "応急処置",
    kind: "skill",
    cls: "neutral",
    energy: 1,
    price: 5,
    rarity: 0,
    textJa: "HP4回復",
    effects: [{ t: "heal", n: 4 }],
  },
  "second-wind": {
    id: "second-wind",
    name: "Second Wind",
    nameJa: "再起",
    kind: "skill",
    cls: "neutral",
    energy: 2,
    price: 9,
    rarity: 1,
    textJa: "HP5回復・1枚ドロー",
    effects: [
      { t: "heal", n: 5 },
      { t: "draw", n: 1 },
    ],
  },
  adrenaline: {
    id: "adrenaline",
    name: "Adrenaline",
    nameJa: "アドレナリン",
    kind: "skill",
    cls: "neutral",
    energy: 0,
    price: 8,
    rarity: 1,
    textJa: "エネルギー1・このカード除去",
    effects: [{ t: "energy", n: 1 }, { t: "exhaust" }],
  },
  "power-up": {
    id: "power-up",
    name: "Power Up",
    nameJa: "力溜め",
    kind: "skill",
    cls: "neutral",
    energy: 1,
    price: 7,
    rarity: 1,
    textJa: "攻撃+3(2T)",
    effects: [{ t: "buffAtk", n: 3, turns: 2 }],
  },
  harden: {
    id: "harden",
    name: "Harden",
    nameJa: "硬化",
    kind: "skill",
    cls: "neutral",
    energy: 1,
    price: 7,
    rarity: 1,
    textJa: "防御+3(2T)",
    effects: [{ t: "buffDef", n: 3, turns: 2 }],
  },
  "exhaust-strike": {
    id: "exhaust-strike",
    name: "Exhaust Strike",
    nameJa: "捨て身打ち",
    kind: "attack",
    cls: "neutral",
    energy: 1,
    price: 9,
    rarity: 2,
    textJa: "9ダメージ・このカード除去",
    effects: [{ t: "dmg", n: 9 }, { t: "exhaust" }],
    combatOnly: true,
  },
  "trap-set": {
    id: "trap-set",
    name: "Set Trap",
    nameJa: "罠設置",
    kind: "action",
    cls: "neutral",
    energy: 1,
    price: 8,
    rarity: 1,
    textJa: "現在地に罠(4dmg)",
    effects: [{ t: "trapNode", dmg: 4 }],
    overworldOnly: true,
  },
  "hex-curse": {
    id: "hex-curse",
    name: "Hex",
    nameJa: "呪詛",
    kind: "action",
    cls: "neutral",
    energy: 1,
    price: 4,
    rarity: 1,
    textJa: "相手に重荷の呪いを押し付ける",
    effects: [{ t: "curseGive", card: "curse-burden" }],
    overworldOnly: true,
  },
  "gloom-hex": {
    id: "gloom-hex",
    name: "Gloom Hex",
    nameJa: "憂鬱の呪詛",
    kind: "action",
    cls: "neutral",
    energy: 1,
    price: 6,
    rarity: 1,
    textJa: "相手に憂鬱の呪いを押し付ける",
    effects: [{ t: "curseGive", card: "curse-gloom" }],
    overworldOnly: true,
  },
  "spike-trap": {
    id: "spike-trap",
    name: "Spike Trap",
    nameJa: "棘罠",
    kind: "action",
    cls: "neutral",
    energy: 2,
    price: 11,
    rarity: 2,
    textJa: "現在地に罠(8dmg)",
    effects: [{ t: "trapNode", dmg: 8 }],
    overworldOnly: true,
  },
  "field-ration": {
    id: "field-ration",
    name: "Field Ration",
    nameJa: "野戦食",
    kind: "skill",
    cls: "neutral",
    energy: 0,
    price: 6,
    rarity: 0,
    textJa: "HP2回復・このカード除去",
    effects: [{ t: "heal", n: 2 }, { t: "exhaust" }],
  },
  "war-cry": {
    id: "war-cry",
    name: "War Cry",
    nameJa: "鬨の声",
    kind: "skill",
    cls: "neutral",
    energy: 1,
    price: 8,
    rarity: 1,
    textJa: "攻撃+2(2T)・1枚ドロー",
    effects: [
      { t: "buffAtk", n: 2, turns: 2 },
      { t: "draw", n: 1 },
    ],
  },
  "quick-patch": {
    id: "quick-patch",
    name: "Quick Patch",
    nameJa: "応急修理",
    kind: "skill",
    cls: "neutral",
    energy: 1,
    price: 6,
    rarity: 0,
    textJa: "HP2回復・2ブロック",
    effects: [
      { t: "heal", n: 2 },
      { t: "block", n: 2 },
    ],
    combatOnly: true,
  },
  "double-jab": {
    id: "double-jab",
    name: "Double Jab",
    nameJa: "二連ジャブ",
    kind: "attack",
    cls: "neutral",
    energy: 2,
    price: 9,
    rarity: 1,
    textJa: "5ダメージ×2",
    effects: [{ t: "dmg", n: 5, times: 2 }],
    combatOnly: true,
  },
  "xp-scroll": {
    id: "xp-scroll",
    name: "XP Scroll",
    nameJa: "経験の巻物",
    kind: "action",
    cls: "neutral",
    energy: 1,
    price: 10,
    rarity: 1,
    textJa: "XP3・このカード除去",
    effects: [{ t: "xp", n: 3 }, { t: "exhaust" }],
  },

  // ── Items (~12) purchasable ───────────────────────────────────────────────
  "item-red-potion": {
    id: "item-red-potion",
    name: "Red Potion",
    nameJa: "赤ポーション",
    kind: "item",
    cls: "neutral",
    energy: 0,
    price: 8,
    rarity: 0,
    textJa: "HP6回復・このカード除去",
    effects: [{ t: "heal", n: 6 }, { t: "exhaust" }],
  },
  "item-blue-potion": {
    id: "item-blue-potion",
    name: "Blue Potion",
    nameJa: "青ポーション",
    kind: "item",
    cls: "neutral",
    energy: 0,
    price: 10,
    rarity: 1,
    textJa: "エネルギー2・このカード除去",
    effects: [{ t: "energy", n: 2 }, { t: "exhaust" }],
  },
  "item-smoke-bomb": {
    id: "item-smoke-bomb",
    name: "Smoke Bomb",
    nameJa: "煙玉",
    kind: "item",
    cls: "neutral",
    energy: 0,
    price: 9,
    rarity: 1,
    textJa: "8ブロック・このカード除去",
    effects: [{ t: "block", n: 8 }, { t: "exhaust" }],
    combatOnly: true,
  },
  "item-throwing-knife": {
    id: "item-throwing-knife",
    name: "Throwing Knife",
    nameJa: "投げナイフ",
    kind: "item",
    cls: "neutral",
    energy: 0,
    price: 9,
    rarity: 1,
    textJa: "8ダメージ・このカード除去",
    effects: [{ t: "dmg", n: 8 }, { t: "exhaust" }],
    combatOnly: true,
  },
  "item-lucky-coin": {
    id: "item-lucky-coin",
    name: "Lucky Coin",
    nameJa: "幸運貨",
    kind: "item",
    cls: "neutral",
    energy: 0,
    price: 5,
    rarity: 0,
    textJa: "コイン7・このカード除去",
    effects: [{ t: "gold", n: 7 }, { t: "exhaust" }],
  },
  "item-swift-boots": {
    id: "item-swift-boots",
    name: "Swift Boots",
    nameJa: "疾風の靴",
    kind: "item",
    cls: "neutral",
    energy: 0,
    price: 11,
    rarity: 1,
    textJa: "移動3・このカード除去",
    effects: [{ t: "move", n: 3 }, { t: "exhaust" }],
    overworldOnly: true,
  },
  "item-ward-amulet": {
    id: "item-ward-amulet",
    name: "Ward Amulet",
    nameJa: "守護のお守り",
    kind: "item",
    cls: "neutral",
    energy: 0,
    price: 10,
    rarity: 1,
    textJa: "防御+3(3T)・このカード除去",
    effects: [{ t: "buffDef", n: 3, turns: 3 }, { t: "exhaust" }],
  },
  "item-fire-scroll": {
    id: "item-fire-scroll",
    name: "Fire Scroll",
    nameJa: "炎の巻物",
    kind: "item",
    cls: "neutral",
    energy: 1,
    price: 12,
    rarity: 1,
    textJa: "12ダメージ・このカード除去",
    effects: [{ t: "dmg", n: 12 }, { t: "exhaust" }],
    combatOnly: true,
  },
  "item-bandage": {
    id: "item-bandage",
    name: "Bandage Kit",
    nameJa: "包帯セット",
    kind: "item",
    cls: "neutral",
    energy: 0,
    price: 6,
    rarity: 0,
    textJa: "HP4回復・このカード除去",
    effects: [{ t: "heal", n: 4 }, { t: "exhaust" }],
  },
  "item-stun-dust": {
    id: "item-stun-dust",
    name: "Stun Dust",
    nameJa: "気絶の粉",
    kind: "item",
    cls: "neutral",
    energy: 1,
    price: 11,
    rarity: 1,
    textJa: "気絶1・このカード除去",
    effects: [{ t: "stun", turns: 1 }, { t: "exhaust" }],
    combatOnly: true,
  },
  "item-poison-vial": {
    id: "item-poison-vial",
    name: "Poison Vial",
    nameJa: "毒瓶",
    kind: "item",
    cls: "neutral",
    energy: 0,
    price: 10,
    rarity: 1,
    textJa: "毒3(3T)・このカード除去",
    effects: [{ t: "poison", n: 3, turns: 3 }, { t: "exhaust" }],
    combatOnly: true,
  },
  "item-bomb": {
    id: "item-bomb",
    name: "Brick Bomb",
    nameJa: "ブリック爆弾",
    kind: "item",
    cls: "neutral",
    energy: 1,
    price: 14,
    rarity: 2,
    textJa: "15ダメージ・このカード除去",
    effects: [{ t: "dmg", n: 15 }, { t: "exhaust" }],
    combatOnly: true,
  },

  // ── Curses (3) ────────────────────────────────────────────────────────────
  "curse-burden": {
    id: "curse-burden",
    name: "Burden",
    nameJa: "重荷",
    kind: "curse",
    cls: "neutral",
    energy: 1,
    price: 0,
    rarity: 0,
    textJa: "効果なし（手札を塞ぐ）",
    effects: [],
  },
  "curse-gloom": {
    id: "curse-gloom",
    name: "Gloom",
    nameJa: "憂鬱",
    kind: "curse",
    cls: "neutral",
    energy: 1,
    price: 0,
    rarity: 0,
    textJa: "HP1失う",
    effects: [{ t: "loseHp", n: 1 }],
  },
  "curse-chains": {
    id: "curse-chains",
    name: "Chains",
    nameJa: "鎖",
    kind: "curse",
    cls: "neutral",
    energy: 2,
    price: 0,
    rarity: 0,
    textJa: "HP2失う・このカード除去",
    effects: [{ t: "loseHp", n: 2 }, { t: "exhaust" }],
  },
};
