import type { MonsterDef } from "../engine/types";

// Envelope (ARCHITECTURE.md):
// t1: HP8-14 ATK2-4 arm0-1 XP3-5 gold4-8
// t2: HP16-26 ATK4-7 arm0-2 XP6-9 gold8-14
// t3: HP28-42 ATK7-10 arm1-3 XP10-14 gold12-20
// elite: HP/XP/gold ×1.5, ATK+1, armor+1 vs tier table
// shrine: HP40-55 ATK8-11 arm2 XP15 gold20
// final: HP70-85 ATK11-13 arm2-3

export const MONSTERS: Record<string, MonsterDef> = {
  // ── Tier 1 regular (4) ────────────────────────────────────────────────────
  "brick-slime": {
    id: "brick-slime",
    name: "Brick Slime",
    nameJa: "ブリックスライム",
    tier: 1,
    hp: 10,
    atk: 3,
    armor: 0,
    traits: [],
    xp: 3,
    gold: [4, 6],
    loot: ["item-bandage", "coin-purse"],
  },
  "stud-bat": {
    id: "stud-bat",
    name: "Stud Bat",
    nameJa: "スタッドコウモリ",
    tier: 1,
    hp: 8,
    atk: 4,
    armor: 0,
    traits: ["first-strike"],
    xp: 4,
    gold: [4, 7],
    loot: ["stride", "jab"],
  },
  "peg-rat": {
    id: "peg-rat",
    name: "Peg Rat",
    nameJa: "ペグラット",
    tier: 1,
    hp: 12,
    atk: 2,
    armor: 1,
    traits: ["thief"],
    xp: 3,
    gold: [5, 8],
    loot: ["coin-purse", "scavenger"],
  },
  "clay-imp": {
    id: "clay-imp",
    name: "Clay Imp",
    nameJa: "クレイインプ",
    tier: 1,
    hp: 14,
    atk: 3,
    armor: 0,
    traits: ["venomous"],
    xp: 5,
    gold: [5, 8],
    loot: ["study", "first-aid"],
  },

  // ── Tier 2 regular (4) ────────────────────────────────────────────────────
  "brick-ogre": {
    id: "brick-ogre",
    name: "Brick Ogre",
    nameJa: "ブリックオーガ",
    tier: 2,
    hp: 24,
    atk: 6,
    armor: 1,
    traits: ["armored"],
    xp: 7,
    gold: [9, 13],
    loot: ["heavy-blow", "iron-wall"],
  },
  "gear-golem": {
    id: "gear-golem",
    name: "Gear Golem",
    nameJa: "ギアゴーレム",
    tier: 2,
    hp: 16,
    atk: 4,
    armor: 2,
    traits: ["armored", "regen"],
    xp: 8,
    gold: [10, 14],
    loot: ["harden", "brace"],
  },
  "plate-wyrm": {
    id: "plate-wyrm",
    name: "Plate Wyrm",
    nameJa: "プレートワーム",
    tier: 2,
    hp: 20,
    atk: 7,
    armor: 0,
    traits: ["venomous"],
    xp: 8,
    gold: [8, 12],
    loot: ["item-poison-vial", "power-up"],
  },
  "mosaic-knight": {
    id: "mosaic-knight",
    name: "Mosaic Knight",
    nameJa: "モザイク騎士",
    tier: 2,
    hp: 26,
    atk: 5,
    armor: 2,
    traits: ["first-strike"],
    xp: 9,
    gold: [10, 14],
    loot: ["war-cry", "item-ward-amulet"],
  },

  // ── Tier 3 regular (4) ────────────────────────────────────────────────────
  "tower-titan": {
    id: "tower-titan",
    name: "Tower Titan",
    nameJa: "タワータイタン",
    tier: 3,
    hp: 40,
    atk: 9,
    armor: 2,
    traits: ["armored", "enrage"],
    xp: 12,
    gold: [14, 18],
    loot: ["exhaust-strike", "item-bomb"],
  },
  "chrome-drake": {
    id: "chrome-drake",
    name: "Chrome Drake",
    nameJa: "クロームドレイク",
    tier: 3,
    hp: 34,
    atk: 10,
    armor: 1,
    traits: ["first-strike", "venomous"],
    xp: 13,
    gold: [13, 19],
    loot: ["item-fire-scroll", "double-jab"],
  },
  "fortress-brute": {
    id: "fortress-brute",
    name: "Fortress Brute",
    nameJa: "砦の巨漢",
    tier: 3,
    hp: 42,
    atk: 8,
    armor: 3,
    traits: ["armored", "regen"],
    xp: 12,
    gold: [15, 20],
    loot: ["iron-wall", "item-red-potion"],
  },
  "prism-wraith": {
    id: "prism-wraith",
    name: "Prism Wraith",
    nameJa: "プリズム幽霊",
    tier: 3,
    hp: 30,
    atk: 9,
    armor: 1,
    traits: ["thief", "enrage"],
    xp: 14,
    gold: [12, 18],
    loot: ["hex-curse", "research"],
  },

  // ── Elite-flavored (3) — tier with elite stats ────────────────────────────
  // t1 elite: HP12-21 ATK3-5 arm1-2 XP≈4.5-7.5 gold6-12
  "elite-stud-captain": {
    id: "elite-stud-captain",
    name: "Stud Captain",
    nameJa: "スタッド隊長",
    tier: 1,
    hp: 18,
    atk: 5,
    armor: 1,
    traits: ["first-strike", "enrage"],
    xp: 7,
    gold: [8, 12],
    loot: ["sprint", "item-throwing-knife", "power-up"],
  },
  // t2 elite: HP24-39 ATK5-8 arm1-3 XP9-13.5 gold12-21
  "elite-gear-warlord": {
    id: "elite-gear-warlord",
    name: "Gear Warlord",
    nameJa: "ギア武将",
    tier: 2,
    hp: 36,
    atk: 8,
    armor: 3,
    traits: ["armored", "regen", "enrage"],
    xp: 12,
    gold: [14, 20],
    loot: ["deep-think", "item-blue-potion", "heavy-blow"],
  },
  // t3 elite: HP42-63 ATK8-11 arm2-4 XP15-21 gold18-30
  "elite-obsidian-king": {
    id: "elite-obsidian-king",
    name: "Obsidian King",
    nameJa: "黒曜石王",
    tier: 3,
    hp: 55,
    atk: 11,
    armor: 3,
    traits: ["armored", "first-strike", "enrage"],
    xp: 18,
    gold: [20, 28],
    loot: ["long-march", "item-bomb", "hex-curse"],
  },

  // ── Shrine guardians (3) ──────────────────────────────────────────────────
  "guardian-crimson-stud": {
    id: "guardian-crimson-stud",
    name: "Crimson Stud",
    nameJa: "紅蓮のスタッド",
    tier: 3,
    hp: 40,
    atk: 8,
    armor: 2,
    traits: ["first-strike", "enrage"],
    xp: 15,
    gold: [20, 20],
    loot: ["item-fire-scroll", "war-cry"],
    guardian: "shrine",
  },
  "guardian-azure-plate": {
    id: "guardian-azure-plate",
    name: "Azure Plate",
    nameJa: "蒼のプレート",
    tier: 3,
    hp: 40,
    atk: 8,
    armor: 2,
    traits: ["armored", "regen"],
    xp: 15,
    gold: [20, 20],
    loot: ["item-ward-amulet", "iron-wall"],
    guardian: "shrine",
  },
  "guardian-golden-peg": {
    id: "guardian-golden-peg",
    name: "Golden Peg",
    nameJa: "金のペグ",
    tier: 3,
    hp: 40,
    atk: 8,
    armor: 2,
    traits: ["venomous", "thief"],
    xp: 15,
    gold: [20, 20],
    loot: ["treasure-map", "item-lucky-coin"],
    guardian: "shrine",
  },

  // ── Final guardian (1) ────────────────────────────────────────────────────
  "guardian-portal-core": {
    id: "guardian-portal-core",
    name: "Portal Core",
    nameJa: "ポータルの核",
    tier: 3,
    hp: 70,
    atk: 11,
    armor: 2,
    traits: ["armored"],
    xp: 0,
    gold: [0, 0],
    loot: [],
    guardian: "final",
  },
};
