/**
 * Generates the Google Fonts links in index.html from the copy that actually
 * ships, and checks that they have not drifted.
 *
 * ## Why this exists
 *
 * The top page cut its JS to 74.6 KB gzip and its images to 250 KB, and then
 * loaded **182,657 gzip bytes of render-blocking CSS** from Google Fonts —
 * more than the JS and the images put together. 780 @font-face blocks:
 *
 *   Noto Sans JP     372   3 weights x 124 unicode-range subsets
 *   Shippori Mincho  366   3 weights x 122
 *   Oswald            15   never rendered: --display[1], behind Barlow
 *   Space Grotesk     12   never rendered: --sans[1], behind Noto Sans JP
 *   Barlow Condensed   9
 *   Space Mono         6
 *
 * None of the repo's gates saw it: measure_closure.mjs weighs JS only, and
 * counts CSS from dist/ — an external stylesheet was outside every ruler.
 *
 * Measured alternatives (gzip, real responses):
 *
 *   current                                        182,657
 *   drop the two unrendered families only          182,331   <- 326 B. Nothing.
 *   trim every family to its used weights           91,623
 *   drop body Japanese, keep the mincho             30,905
 *   all Japanese on system fonts                       620
 *   THIS: latin full + both JP subset to real text   5,400
 *
 * The intuition that "removing unused families is the win" was wrong by two
 * orders of magnitude. The cost is per-WEIGHT of a Japanese family, because
 * each weight expands to ~122 subset declarations.
 *
 * Subsetting to the glyphs the page actually contains keeps both typefaces
 * rendering exactly as they do today and removes 177 KB from the critical
 * path.
 *
 * ## Two links, not one
 *
 * `text=` applies to EVERY family in the request. A single link with all four
 * families returned Barlow Condensed and Space Mono restricted to the
 * Japanese unicode range — every English heading would have fallen back to
 * Arial Narrow. Latin families therefore get their own, unsubsetted link.
 *
 * ## Why generated rather than pasted
 *
 * A hand-written glyph list drifts the first time anyone edits a sentence,
 * and the failure is nasty: the one new character falls back to a system
 * font mid-word while its neighbours stay in Shippori Mincho. Same reason
 * sitemap.ts and optimize_covers.py generate rather than trust — and both
 * ship a --check that fails the gate on drift.
 *
 * Run: npx tsx scripts/fonts.ts          (rewrite index.html)
 *      npx tsx scripts/fonts.ts --check  (fail if stale)
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

/*
 * Every file whose text can reach the top page. index.html itself is included
 * because <title> and the meta descriptions are Japanese too — they do not
 * use the webfont, but a future <noscript> or inline heading would, and
 * including them costs a handful of glyphs.
 */
const SOURCES = [
  "index.html",
  "src/portfolio/App.tsx",
  "src/portfolio/components/AiLab.tsx",
  "src/portfolio/components/BentoTile.tsx",
  "src/portfolio/components/CursorFX.tsx",
  "src/portfolio/components/EditorialHero.tsx",
  "src/portfolio/components/Footer.tsx",
  "src/portfolio/components/GameDetail.tsx",
  "src/portfolio/components/Prompts.tsx",
  "src/portfolio/components/SiteNav.tsx",
  "src/portfolio/components/StackStrip.tsx",
  "src/portfolio/components/WorksBento.tsx",
  "src/portfolio/components/badges.tsx",
  "src/data/works.ts",
  "src/data/arenaGames.ts",
  "src/data/comparisons.ts",
  "src/data/prompts.ts",
];

/*
 * CJK, kana, kana punctuation, and fullwidth forms. Latin/digits are excluded
 * on purpose: they come from the unsubsetted latin link, and adding them here
 * would only inflate the Japanese subset with glyphs it already has covered.
 */
const JAPANESE =
  /[　-〿぀-ゟ゠-ヿㇰ-ㇿ一-鿿＀-￯]/u;

/** Sorted so the URL is stable across runs — an unstable URL breaks caching. */
export function collectGlyphs(): string {
  const found = new Set<string>();
  for (const relative of SOURCES) {
    const text = readFileSync(join(root, relative), "utf8");
    for (const character of text) {
      if (JAPANESE.test(character)) found.add(character);
    }
  }
  return [...found].sort().join("");
}

const LATIN_LINK =
  "https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@600;700" +
  "&family=Space+Mono:wght@400;700&display=swap";

export function japaneseLink(glyphs: string): string {
  return (
    "https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@400;700" +
    "&family=Shippori+Mincho:wght@500" +
    `&text=${encodeURIComponent(glyphs)}&display=swap`
  );
}

const BEGIN = "<!-- fonts:begin (generated by scripts/fonts.ts — do not edit) -->";
const END = "<!-- fonts:end -->";

function block(glyphs: string): string {
  return [
    BEGIN,
    '    <link rel="preconnect" href="https://fonts.googleapis.com" />',
    '    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />',
    `    <link href="${LATIN_LINK}" rel="stylesheet" />`,
    `    <link href="${japaneseLink(glyphs)}" rel="stylesheet" />`,
    `    ${END}`,
  ].join("\n    ");
}

function main(): void {
  const check = process.argv.includes("--check");
  const indexPath = join(root, "index.html");
  const html = readFileSync(indexPath, "utf8");
  const glyphs = collectGlyphs();
  const wanted = block(glyphs);

  const start = html.indexOf(BEGIN);
  const stop = html.indexOf(END);
  if (start === -1 || stop === -1) {
    console.log("FONTS FAIL — index.html has no fonts:begin/fonts:end markers");
    process.exitCode = 1;
    return;
  }
  const current = html.slice(start, stop + END.length);

  if (current === wanted) {
    console.log(`FONTS PASS — ${glyphs.length} 和文グリフ / 2 links`);
    return;
  }
  if (check) {
    console.log(
      `FONTS FAIL — index.html のフォントリンクが古い（現在のソースは ${glyphs.length} 字）。` +
        " npx tsx scripts/fonts.ts で再生成すること"
    );
    process.exitCode = 1;
    return;
  }
  writeFileSync(indexPath, html.slice(0, start) + wanted + html.slice(stop + END.length));
  console.log(`FONTS WRITTEN — ${glyphs.length} 和文グリフ / 2 links`);
}

main();
